bcgov/namex

- api/app/resources/document_analysis.py
- api/tests/postman/namex-common.postman_collection.json
*Issue #, if available:* bcgov/name-examination#549
Exposed the Solr queries under request analysis as generic text search.
The URL pattern is based on the Google Document Analysis API, which is similar to the Microsoft Azure Documents API. This should be familiar then to other developers.
> updates to document search

- api/migrations/env.py
- docs/database.md
*Issue #, if available:* #bcgov/name-examination560
*Description of changes:* Altered Alembic ENV to ignore tables not managed by the model. Updated the global DB docs with a note to reflect that.
> bcgov/name-examination#560 Make Alembic ignore existing db tables when creating migrations

- api/app/resources/document_analysis.py
*Issue #, if available:* https://github.com/bcgov/name-examination/issues/628
*Description of changes:* Removed the escaping of the query string on input, as it was being escaped twice. This was causing words containing apostrophes to basically be excluded as search terms.
> Update Solr API to handle apostrophes in search terms #628

- api/app/analytics/solr.py
*Issue #, if available:* 102
*Description of changes:* Update the Solr API for history to include the existing field name_state_type_cd and the new field submit_count.
> Update Solr API to add fields for history queries

- api/requirements/prod.NoVer.txt
- api/requirements/prod.txt
*Issue #, if available:* NA
*Description of changes:* Moved namex to use the JWT library from PyPi
> Use jwt library from PyPi

- api/namex/models/request.py
Removed expirationDate from PUT, because a) we're not converting it from string to timestamp, so it's failing validation, and b) we don't actually let user edit it so it doesn't matter.
> bug fix: Removed expirationDate from PUT

- api/namex/models/event.py
- api/namex/resources/requests.py
- api/namex/services/__init__.py
- api/namex/services/audit_trail/__init__.py
- api/namex/services/audit_trail/event_recorder.py
*Issue #, if available:* bcgov/name-examination#751
adding EventRecorder service back into the API to record what was changed and by whom.
The service will add an Event to the system, so easier to track fields of Datetime, User, Request, State and the json input that modified the record.
Not sure if the NRO Extractor should use this, but it might be a good idea to do so, as that would sort of give us a reverse delta history if you wanted to run/view changes to see what the Request looked like at a point in time.
> adding EventRecorder service back into the API

- solr-admin-app/docs/readme.md
- solr-admin-app/model/user.py
- solr-admin-app/solr_admin/views/synonym_view.py
*Issue #, if available:* 774
*Description of changes:* removed the validation that disallowed embedded spaces in synonyms.
> Allow embedded spaces in Solr synonyms. #774

- api/namex/services/nro/oracle_services.py
- nro-update/nro/nro_datapump.py
- nro-update/nro_update.py
Bug fixes:
- NRO Updater:
-- set decision text for rejected names (was missing check for rejected)
-- pick up CONDITIONAL request types in NRO Update (was missing check
for conditional)
-- condition on Furnished flag correctly (python style "is not "Y" not
working in SQL statement)
- NRO Services in API:
-- substring username to 7 chars to match TRANSACTION.BCOL_RACF_ID table
used by name_examination() proc.
> Bug fixes - NRO Updater and NRO Services in API

- api/namex/analytics/solr.py
- api/tests/python/solr/test_query_string.py
*Issue #, if available:* 728
*Description of changes:* Added use of the @ character to indicate that the following word or quoted phrase is not to be run through the synonyms.
> Change Solr API to allow not synonymizing #728

- solr-admin-app/docs/readme.md
- solr-admin-app/solr_admin/views/synonym_view.py
*Issue #, if available:* 775
*Description of changes:* updated the validation to restrict synonym text to a-z, 0-9, and space.
> Restrict characters allowed in synonyms. #775

- solr/cores/names/conf/managed-schema
- solr/cores/possible.conflicts/conf/managed-schema
- solr/cores/trademarks/conf/managed-schema
*Issue #, if available:* 803
*Description of changes:* Added the flatten graph filters back to each of the three cores.
> Restored the FlattenGraphFilter for indexing. #803

- solr-feeder/solr_feeder/endpoints/feeds.py
- solr-feeder/solr_feeder/models/completed_nr.py
*Issue #, if available:* 527
*Description of changes:* updated the feeder to handle multiple results for a single NR. Turns out that the name instance ID is the PK, not the NR number. Added a loop to do multiple updates per NR, and to only do names of state A and C for the conflicts core.
> Added the Solr feeder project. #527

- solr/cores/names/conf/synonyms.txt
- solr/cores/possible.conflicts/conf/synonyms.txt
- solr/cores/trademarks/conf/synonyms.txt
*Issue #, if available:* 811
*Description of changes:* dummy synonyms.txt files were previously added, as a temporary measure to get rid of the stuck synonyms..txt files that were not being deleted. Once again the synonyms.txt files have been deleted - it's assumed that they will again be stuck, but at least the content of the stuck files will be less confusing.
> Deleted empty synonynms.txt files. #811

- nro-update/nro_update.py
- nro-update/openshift/templates/cron-nro-update.yml
*Issue #, if available:* 424
altering the sqlalchemy calls so that they can be printed fully in debug mode. altering the cronjob to force the image to come from the registry and not use the cached version.
> updates to support better debugging and ensure current image is used.

- solr/openshift/solr-deploy.DEV.param
- solr/openshift/solr-deploy.PROD.param
- solr/openshift/solr-deploy.TEST.param
- solr/openshift/templates/solr-deploy-local.json
- solr/openshift/templates/solr-deploy.json
*Issue #, if available:* 872
*Description of changes:* Removed the trademarks storage from the deploy scripts and environment-specific parameters files.
> Removed unused trademarks storage. #872

- solr-admin-app/app.py
- solr-admin-app/config.py
- solr-admin-app/docs/readme.md
- solr-admin-app/solr_admin/views/synonym_audit_view.py
- solr-admin-app/solr_admin/views/synonym_view.py
*Issue #, if available:* 876
*Description of changes:* Set up the solr admin app so that test is the sole environment in which data can be edited.
> Made synonyms editable only in test environment. #876

- api/namex/services/nro/oracle_services.py
- api/namex/services/nro/utils.py
- api/tests/python/nro_services/test_nro_utils.py
*Issue #, if available:* bcgov/name-examination#887
887 removing the SSI portion of the username and trunc to 7 chars for NRO
> 887 set username in NRO correctly

- nro-extractor/api/endpoints/requests.py
- nro-extractor/tests/unit/test_requests.py
*Issue #, if available:* bcgov/name-examination#902
ensure priority flag is set when nro is set to PQ
add test to ensure all 4 known permutations in the priority setting are handled
> ensure Priority status is set

- nro-extractor/api/endpoints/requests.py
- nro-extractor/tests/unit/test_requests.py
*Issue #, if available:* bcgov/name-examination#921
If the Name Request in NRO is in a COMPLETED state, we need to set the Request state in NameX based on what the name_state is. All the other request states should behave the same.
There is a series of tests to exercise the various permutations.
> set request state in NameX whin loading COMPLETED requests from NRO

- nro-legacy/sql/object/names/namex/package/namex_pkb.sql
*Issue #, if available:* bcgov/name-examination#924
Changed the loader to process status 'C' in addition to 'D'
> add the C (CANCL) state to the load mechanism

- colin-api/app/resources/corporations.py
*Issue #, if available:* 919
API now handles corporations that exist, but are not in the corp_num_dts_class_vw
> colin-api incomplete data handling update

- api/namex/analytics/solr.py
- api/tests/python/solr/test_query_string.py
*Issue #, if available:* 960
*Description of changes:* Fixed the @ handling code to behave correctly when there is no term following the @ sign.
> Solr API bugfix for @ in unexpected locations. #960

- docs/Backend-namex_api_setup.md
- Updated the API setup docs to add a Mac section for the interpreter in the IDE.
- Removed secrets file as it's no longer used in the API
- other minor changes
> Clean up mac section in interpreter section

- api/namex/models/name.py
- api/namex/resources/requests.py
*Issue #, if available:* bcgov/name-examination#983
Force NR names to be uppercase. Done in Request PUT (where the name edits are handled) as well in the name save_to_db() function, even though that function is not used for name edits at this time.
> Force NR names to be uppercase.

- solr/Jenkinsfile
*Issue #923:*
pipeline shouldn't error on dev deploy anymore.
> solr pipeline bug fix

- api/Jenkinsfile
- attachment var already initialized in 2 places so removed initialization with 'def'
> namex-api-pipeline bug-fix

- solr-synonyms-api/synonyms/models/synonym.py
*Issue #, if available:* 1039
*Description of changes:* Fixed a bug where the DB query was ignoring case but subsequent string comparisons were not.
> Solr: API query with synonyms. #1039

- solr/cores/trademarks/conf/managed-schema
*Issue #, if available:*1109
registration_number was added to the Trademarks core so that it can be displayed to examiners in search results. It is not the uniqueKey, but it is required.
Next steps: modify the parser to pull this field from the XML into the JSON file used for loading the index.
> Added registration_number to Trademarks managed-schema

- api/namex/analytics/solr.py
- api/tests/python/__init__.py
- api/tests/python/solr/test_query_string.py
- api/tests/python/solr/test_solr.py
- api/tests/python/util.py
*Issue #, if available:* bcgov/name-examination#1075
Added a tokenizer that doesn't create as many temporary objects by using slices.
Broke it into a tokenizer and then a parser for synonyms. The tokenizer could be used for the other parsers as well.
Added tests for the 2 new methods
Added a test to confirm the query string that is sent to Solr is as expected.
> 1075 solr synonyms

- api/namex/models/name.py
- api/tests/python/models/test_names.py
*Issue #, if available:* bcgov/name-examination#1108
Replace NR number conflicts with generic "NR 0000000"
> Replace NR number conflicts with generic "NR 0000000"

- api/namex/models/name.py
- api/tests/python/models/test_names.py
- nro-update/nro/nro_datapump.py
*Issue #, if available:* bcgov/name-examination#1130
Roll back change to replace NR conflict with "NR 0000000"; clear data when pushing to Oracle only, replacing with "NR".
> Roll back change to replace NR conflict with "NR 0000000"; clear data when pushing to Oracle only, replacing with "NR".

- nro-legacy/sql/object/names/namex/view/solr_dataimport_conflicts_vw.sql
- nro-legacy/sql/release/201810XX_solr_bugs/names/namex/create.sql
*Issue #, if available:* 1147
*Description of changes:* fixed the names view for conflicts, as it was excluding NRs that expire at the end of the current day.
> Solr: fixed NR expiry date logic. #1147

- solr/cores/trademarks/conf/managed-schema
*Issue #, if available:* 1118
*Description of changes:* Made the new field registration_number in the trademarks core to not be required. It only appears in around 75% of the records.
> Set the trademarks registration number to not be required. #1118

- nro-legacy/sql/object/names/namex/package/solr_pkb.sql
- nro-legacy/sql/release/201810XX_solr_bugs/names/namex/create.sql
*Issue #, if available:* 1138
*Description of changes:* accented characters were causing problems with the Solr feeder. Converted the data sent to the feeder to be UTF-8.
> Solr: convert feed data to UTF8. #1138

- .gitignore
- api/namex/resources/__init__.py
- api/namex/resources/exact_match.py
- api/requirements/prod.txt
- api/tests/python/end_points/test_exact_match.py
- solr/cores/possible.conflicts/conf/managed-schema
a new end point to fetch the exact matches for a name.
Call is tlike /exact-match?query=incredible
> /exact_match now returns id, source, name for each entry

- api/namex/resources/exact_match.py
- api/requirements/dev.txt
- api/requirements/prod.txt
- api/tests/python/end_points/test_exact_match.py
- solr/cores/possible.conflicts/conf/managed-schema
use urllib in prod
explore writing tests the @pytest.mark.parametrize way
handle more exact-match cases
> 1159 - we now handle more complex cases

- api/tests/python/end_points/test_exact_match.py
- solr/cores/possible.conflicts/conf/managed-schema
exact match now handles @, =, +, or, -, _
> exact match now handles @, =, +, or, -, _

- colin-api/app/resources/corporations.py
- colin-api/tests/unit/conftest.py
- colin-api/tests/unit/test_addr_id_sql.py
- nro-legacy/sql/object/registry/namex/view/office_vw.sql
- nro-legacy/tests/postgres.py
- nro-legacy/tests/test_office_vw.py
We now implement the [not null delivery_addr_id and null end_event_id] in the api instead of in the oracle view
> better fix for issue #18

- api/namex/analytics/solr.py
- api/namex/resources/exact_match.py
- api/requirements/dev.txt
- api/tests/python/end_points/test_exact_match.py
- api/tests/python/end_points/test_synonym_match.py
- solr/cores/possible.conflicts/conf/managed-schema
*Issue #, if available:bcgov/entity#12*
- solr tuning on synonym bucket call + exact match call
- synonym bucket:
- stop words, s, ', designations (if at the end), double letters
- exact match:
- removal of * 
> 12 solr tuning manual search

- jobs/nro-extractor/run.sh
changed job target in run.sh from job.py to nro_extractor.py
> fix job name in run.sh

- api/namex/resources/requests.py
*Issue #, if available:* bcgov/namex#31
31 - Additional change re. setting back to DRAFT - when is mid-edit and navigates away to another NR and starts exam/edit (makes it their new INPROGRESS NR).
> 31 - Additional change re. setting back to DRAFT.

- api/namex/services/nro/oracle_services.py
- api/tests/python/end_points/test_requests.py
- api/tests/python/nro_services/test_nro_services.py
*Issue #, if available:* bcgov/entity#56
added check for when NR exists in NameX, but not NRO. Probably only happens in non-prod environments
> fix situation where Request exists in NameX but not NRO

- api/migrations/versions/84ea2594fc08_.py
- api/namex/models/request.py
- jobs/nro-update/nro/nro_datapump.py
- jobs/nro-update/requirements/prod.txt
- jobs/nro-update/tests/test_nro_datapump.py
*Issue #, if available:* bcgov/entity#50
api: Altered the storage params for Request.expiry_date to be stored with timezone 
nro-update: added new func to calculate expiry date, updated tests to check for before/after 4pm PST to ensure the correct PST date is set. Check that the correct date is being sent to NRO.
> set expiry date based on utc storage, and us/pacific enforcement time

- api/namex/analytics/solr.py
- multiple spaces between words in a name caused synonyms being returned in brackets to have weird behavour <- fixed by replacing multiple spaces with a single space
> bug-fix for synonyms

- api/namex/resources/requests.py
*Issue #, if available:* bcgov/entity#72
Scanned for all usages of find_by_nr and put in check to return 404 there, before the nr was referenced.
> scanned api for Request.find_by_nr (and find_by_name) - altered to return 404 if None

- api/namex/services/nro/change_nr.py
- api/namex/services/nro/utils.py
- api/tests/python/nro_services/test_nro_utils.py
Issue # bcgov/entity#77
If a name is edited in NAMEX, the NAMESP.NAMESDB.name_instance.search_name value is not being set to the "compressed" or "search" name. This means that if the user does a name search in NRO, the proper name requests are not being found.
Soultion:
Add a compressed name function into utils.py;
--Set uppercase;
--Remove "THE "and " THE ";
--Remove space;
--Remove chars not in 'ABCDEFGHIJKLMNOPQRSTUVWXYZ#&0123456789';
--Translate the char into words;
--Translate "BRITISHCOLUMBIA" into "BC";
--The name length is limited to 30 characters;
Add test;
Call the compressed name function when insert a record into name instance table;
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex …
> #77 compress search name

- nro-legacy/sql/object/registry/namex/view/solr_dataimport_conflicts_vw.sql
- nro-legacy/sql/release/201901XX_solr_view/registry/namex/create.sql
- nro-legacy/tests/seeds.py
- nro-legacy/tests/sql/create.table.corp.name.sql
- nro-legacy/tests/sql/create.table.corp.op.state.sql
- nro-legacy/tests/sql/create.table.corp.state.sql
- nro-legacy/tests/sql/create.table.corp.type.sql
- nro-legacy/tests/sql/create.table.corporation.sql
- nro-legacy/tests/test_solr_corp_vw.py
https://github.com/bcgov/entity/issues/55
Changes the corporate solr view to include assumed  names.  Tests use postgres rather than oracle locally.
> Assumed Name View Changes and tests.

- api/namex/analytics/phonetic/__init__.py
- api/namex/analytics/solr.py
- api/tests/python/end_points/test_sounds_like.py
44
The order of the sounds is now respected so that leading vowels no longer match words with leading consonants in unexpected ways.
e.g.: "eh" no longer matches "herb"
> Corrected matching on leading vowels

- api/config.py
- api/namex/models/request.py
- api/namex/resources/requests.py
- api/tests/postman/namex-pipeline-dev.postman_collection.json
- api/tests/postman/namex-pipeline-test.postman_collection.json
*Issue #, if available:* bcgov/entity#21
Upon reset, add generated comment.
This follows the same approach as name change generated comment, ie: in API rather than front-end.
> Upon reset, add generated comment.

- api/namex/resources/requests.py
- api/namex/services/name_request/__init__.py
- api/namex/services/nro/change_nr.py
- api/tests/python/nro_services/test_update_request.py
*Issue #, if available:* bcgov/entity#26 + bcgov/entity#40
Set NR back to Draft ("D") in NRO when set back to Draft in Namex, for regular edits as well as RESET.
> Set NR to draft in NRO when set to draft in Namex.

- nro-legacy/sql/release/20190202_oracle_12/names/namex/update.sql
*Issue #, if available:* 15
*Description of changes:* added an update script to be run on the NAMES database after the upgrade to Oracle 12.
> Update Oracle wallet location on Oracle 12 servers. #15

- api/namex/analytics/solr.py
- parsing the name at the beginning of 'get_conflict_results' in 'solr.py' caused problems for searching wildcard + proximity search
- fix: changed where we parse the name so that it still prevents any 500 errors, but also doesn't mess with the searches
- pytests pass
> conflict search bug fixed

- api/namex/services/nro/change_nr.py
- api/namex/services/nro/oracle_services.py
- api/tests/python/nro_services/test_update_request.py
*Issue #, [bcgov/entity#36](https://github.com/bcgov/entity/issues/36):*
Add a new create cancel status transaction function and modify the change nr function when NR get cancelled.
> Set cancel status instead of admin status when cancel a NR

- api/namex/resources/requests.py
bcgov/entity#97
Update the call for the nr get so that it only requires one of the listed roles.
> Update call to require only one of the given roles instead of all

- api/namex/analytics/solr.py
- api/tests/python/end_points/test_synonym_match.py
Signed-off-by: PWEI <patrick.wei@gov.bc.ca>
[bcgov/entity#65](https://github.com/bcgov/entity/issues/65)
Using parse quote function to encode non-ASCII characters one by one of search name.
> Add code to handle Non-ASCII characters only

- api/namex/analytics/solr.py
- api/tests/python/end_points/test_synonym_match.py
*Issue #, if available:bcgov/entity#69 bcgov/entity#74*
- changes for dealing with multi-word-syns properly
> 69 74 highlighting syns stems bug fixes

- api/namex/analytics/solr.py
- api/tests/python/end_points/test_synonym_match.py
*Issue #, if available: bcgov/entity#69 bcgov/entity#74*
- logic error fixed in method that finds the stems for each word
> fixed stem list for edge case stems(property, equity, etc.)

- api/namex/resources/requests.py
- api/namex/services/name_request/__init__.py
- api/tests/postman/namex-pipeline-dev.postman_collection.json
- api/tests/postman/namex-pipeline-test.postman_collection.json
*Issue #, if available:* bcgov/entity#118
Per request, change workflow (mainly in front-end) of RESET functionality based on role. Step 1 for all roles is to set to INPROGRESS so NR cannot be "stolen" by another user.
There is a corresponding front-end PR required.
> Upon reset/re-open, change NR state to INPROGRESS rather than DRAFT.

- api/config.py
Altered config.py to add caching of the JWKS, ansd set the cachetimeout to be an int() as required by the werkzeug caching for type comparison. 
> Jwt cache config

- api/namex/models/name.py
- api/namex/resources/requests.py
- api/namex/services/nro/change_nr.py
- api/tests/python/end_points/test_requests.py
- api/tests/python/nro_services/test_update_request.py
bcgov/entity#54
Check whether new name is blank before adding a new row to the name_instance table in nro.
> Allow a name to be removed from nro name_instance table

- api/namex/analytics/solr.py
- api/tests/python/end_points/test_synonym_match.py
*Issue #, if available:bcgov/entity#69 bcgov/entity#74*
- fixed bug where search would filter out names that included synonyms part of more than 1 synonym list (if a name was returned because it had a synonym of what was searched and that synonym was not in the first list of synonyms for that word it would get filtered out)
- pytests added/pass locally
- logging error message also fixed 
> search no longer filters names with synonyms from multiple synonym lists

- docs/legacy/nro_datapump_pkg_body.sql
- nro-legacy/sql/object/names/namesdb/package/nro_data_pump_pkg.sql
- nro-legacy/sql/object/names/namesdb/package/nro_datapump_pkg_body.sql
- nro-legacy/sql/release/20190206_datapump/names/namesdb/update.sql
[bcgov/entity#111](https://github.com/bcgov/entity/issues/111)
Update oracle package NRO_DATAPUMP_PKG.name_examination function and set state_comment to NULL if it is a empty string.
> Save the state_comment value to NULL when it is a empty string 

- api/migrations/versions/21b953f6b653_.py
- api/namex/models/name.py
- api/namex/models/nwpta.py
- api/namex/models/request.py
- api/namex/services/nro/oracle_services.py
- api/namex/services/nro/request_utils.py
- api/requirements/prod.txt
- api/setup.cfg
- api/tests/python/end_points/test_requests.py
*Issue #, if available:* bcgov/entity#37
- added callback to oracle session to set TZ to Vancouver
- added Oracle calls to change dates to sys_extract_utc dates
- added sys_extract_utc to nro_services calls
- updated models for the remaining dates to be stored with TZ data
- added migration script, including migrating the data from old PST to UTC
- changed requirements/prod.txt to hold marshmallow to < v3
> 37 complete dates to utc

- jobs/nro-extractor/openshift/templates/cron-nro-extractor.yml
- jobs/nro-update/openshift/templates/cron-nro-update.yml
*Issue #, if available:* 177
*Description of changes:* Changed nro-extractor and nro-updater to run all day, rather than only during business hours.
> Changed cron nro extractor and updater to run 24x7. #177

- api/namex/analytics/solr.py
- api/tests/python/end_points/test_synonym_match.py
- this fixes a logic error that caused some names to get filtered out of the result set on the backend
> bug fixed with test

- api/namex/analytics/solr.py
- api/tests/python/end_points/test_cobrs_phonetic_match.py
*Issue #, if available:* 185
*Description of changes:* Removed the double-check of existence in array that was causing results to be left out of the solr response.
> Fix names missing from synonyms match. #185

- api/namex/analytics/solr.py
- api/namex/resources/requests.py
- api/tests/postman/namex-pipeline-dev.postman_collection.json
- api/tests/postman/namex-pipeline-test.postman_collection.json
- api/tests/python/end_points/test_cobrs_phonetic_match.py
- api/tests/python/end_points/test_sounds_like.py
- api/tests/python/end_points/test_synonym_match.py
- solr/cores/possible.conflicts/conf/managed-schema
*Issue #, if available:bcgov/entity#108*
- added exact_phrase field in request
- added contains_exact_phrase field in managed_schema
- used as a fq to narrow result set on that phrase
- pm + pytests added (all pass)
- should be coordinated with frontend PR otherwise frontend will error with 404
> 108 search single exact

- api/namex/services/nro/oracle_services.py
- api/tests/python/nro_services/test_nro_services.py
- nro-legacy/sql/object/names/namesdb/package/nro_datapump_pkg.pkb
- nro-legacy/sql/object/names/namesdb/package/nro_datapump_pkg.pks
- nro-legacy/sql/object/names/namesdb/procedure/application_log_insert2.sql
- nro-legacy/sql/release/20190219_namesdb_package/package_updates.sql
- nro-legacy/sql/release/20190220_namesdb/package/package_updates.sql
- nro-legacy/sql/release/20190220_namesdb/procedure/create.sql
> 137 get resp name examination func

- solr/database/solr_conflicts_core_vw.sql
*Issue #, if available:* 457
*Description of changes:* Fixed a bug in the new view where name requests like FR are being included (although always inactive). They shouldn't even be in the view.
> Added view for conflicts core delta updates. (#457)

- nro-legacy/sql/object/names/namex/package/namex_pkb.sql
- nro-legacy/sql/release/201905XX_namex/names/namex/create.sql
*Issue #, if available:* bcgov/entity#508
Added CONSUME transaction handling in namex feeder; handle in a way that does not include unexpected COMPLETED transactions.
Note: CONSUME transaction type was previously added to condition, but is never executed - see ticket for notes.
> Added CONSUME transaction handling in namex feeder

- solr/database/solr_conflicts_core_vw.sql
- solr/database/solr_names_core_vw.sql
*Issue #, if available:* 543
*Description of changes:* There was a bug where an NR on HOLD that had previously been examined and then RESET would should up as an ACTIVE name. It should be INACTIVE. Also fixed the ownership of some objects and made column sources more explicit.
> Fixed bug for held names, cleaned up scripts (#543)

- nro-legacy/sql/object/names/namex/view/solr_dataimport_namesfix_vw.sql
- nro-legacy/sql/object/registry/namex/view/solr_dataimport_conflictsfix_vw.sql
- nro-legacy/sql/release/20190502_solr_views/names/namex/create.sql
- nro-legacy/sql/release/20190502_solr_views/registry/namex/create.sql
*Issue #, if available:* 524
*Description of changes:* Added new versions of the Solr dataimport views that fix problems. This will allow the new Solr delta import cores to do comparisons against Oracle and ensure we stay in sync.
> New views for comparing Solr cores. (#524)

- e2e/Jenkinsfile
- e2e/nightwatch.json
- e2e/package.json
- e2e/templates/bddstack.bc.yaml
712
Updated image and changed Nightwatch config to run both Chrome and Firefox
Updated to the latest version of nightwatch.
Note: the scripts themselves will fail on a later assertion, but won't be refactored until after the UI refresh is complete.
> Entity#712 add firefox to e2e

- nro-legacy/sql/object/names/namex/package/solr_pkb.sql
- nro-legacy/sql/object/registry/namex/package/solr_pkb.sql
Signed-off-by: Lorna Trent <lorna.trent@gov.bc.ca>
date format did no work for solr feeder.  needed to be converted to a string timestamp in the format solr expected.
> corrected timestamp for solr feeder

- api/requirements/prod.txt
Caused a 400 when using anything higher than 2.19.2 for the name schema used to make decisions in namex.
> Must be this marshmallow version for names schema

- api/namex/analytics/solr.py
Address missing jurisdictions in colin in production that causes a 500 error in the phonetic solr search
> added empty string handling for candidate

- api/namex/models/request.py
- api/namex/services/name_request/auto_analyse/name_analysis_director.py
- api/namex/services/name_request/name_analysis_builder_v2/name_analysis_builder.py
*ANALYZE NAME-Correct Conflicts Query to Deal with Leading Space in the Names #3131*
Exact match not working properly because both leading and trailing spaces before it pass the name to auto-analyze so in the conflict search the original name is "FLASH PACK PACKAGING AND SHIPPING LTD.", the one in the database conflict list is " FLASH PACK PACKAGING AND SHIPPING LTD." so it doesnt find it as an exact match. In addition, it is needed to clean the name before any comparison.
> 3129 exact matches spaces punctuation

- api/namex/services/name_processing/name_processing.py
- api/namex/services/name_request/auto_analyse/mixins/get_designations_lists.py
- api/namex/services/name_request/auto_analyse/name_analysis_utils.py
- api/namex/services/name_request/auto_analyse/protected_name_analysis.py
- api/namex/services/name_request/auto_analyse/unprotected_name_analysis.py
- api/namex/services/name_request/name_analysis_builder_v2/name_analysis_builder.py
- api/namex/services/synonyms/__init__.py
- api/namex/services/synonyms/mixins/designation.py
- api/namex/services/synonyms/synonym.py
- api/tests/python/namex_services/name_request/test_name_analysis_utils.py
- api/tests/python/namex_services/synonyms/__init__.py
- api/tests/python/namex_services/synonyms/test_synonym.py
*ANALYZE NAME-Strip Out All Numbers for Conflict Matching #3141*
All numbers must be stripped out for conflict matching accept when the name is using a stand-alone.Right now numbers are being stripped out of the beginning but not the end and not the middle.
> 3141 v2 strip out numbers

- api/namex/services/name_request/auto_analyse/abstract_name_analysis_builder.py
- api/namex/services/name_request/auto_analyse/name_analysis_director.py
- api/namex/services/name_request/name_analysis_builder_v2/name_analysis_builder.py
*#3158, Remove checks from well formed name:*
- Take out word limit and unclassified checking from well_formed
- If any stopper is present (Add distinctive, Add descriptive, words to avoid and too many words), then stop conducting further checks and return response.
> 3158 remove checks from well formed name

- api/namex/services/name_processing/name_processing.py
- api/namex/services/name_request/name_analysis_builder_v2/name_analysis_builder.py
- api/namex/services/virtual_word_condition/virtual_word_condition.py
- api/namex/utils/common.py
- api/requirements/prod.txt
- solr-synonyms-api/synonyms/services/synonyms/mixins/designation.py
- solr-synonyms-api/synonyms/services/synonyms/synonym.py
*#3281, Not Handling Restricted Words/Consent Words with Numbers:*
-Keep together words containing letters and numbers such as 4H
-Apply singular/plural to every word in the name to match cases such as SUMMERS GAMES 
-Fixes in regex related to designations found during testing designations with dots and without.
> 3281 v2 not handling restricted words number

- api/namex/services/name_processing/__init__.py
- api/namex/services/name_processing/mixins/get_synonym_lists.py
- api/namex/services/name_processing/name_processing.py
- api/namex/services/name_request/auto_analyse/mixins/get_designations_lists.py
- api/namex/services/name_request/auto_analyse/protected_name_analysis.py
- solr-synonyms-api/synonyms/services/synonyms/mixins/designation.py
*# 3429: Show both English and French for the EntityType in All Designation Response Lists:*
-Add French designations to English designations in processing and response. For instance, remove designations in regex_transform now considers French/English designations and response related to possible designations to be used include French and English version.
> 3429 show both english french designation for all designation

- api/namex/services/name_processing/name_processing.py
- api/namex/services/name_request/name_analysis_builder_v2/name_analysis_builder.py
- solr-synonyms-api/synonyms/endpoints/synonyms.py
- solr-synonyms-api/synonyms/services/synonyms/synonym.py
#3387, Slashes and Prefix Issues:*
Words with prefix at the beginning separated by slash, hyphen or space are set together. Then, PRE/SCHOOL becomes PRESCHOOL.
This uses regex-prefixes endpoint in solr-synonyms-api
> 3387 slashes and prefixes issues

- api/namex/resources/auto_analyse/analysis_issues.py
- api/namex/resources/auto_analyse/analysis_response.py
- api/namex/resources/auto_analyse/response_objects/name_action.py
- api/namex/services/name_processing/mixins/get_synonym_lists.py
- api/namex/services/name_processing/name_processing.py
- api/namex/services/name_request/auto_analyse/mixins/get_designations_lists.py
- api/namex/services/name_request/auto_analyse/name_analysis_utils.py
- api/namex/services/name_request/auto_analyse/protected_name_analysis.py
- solr-synonyms-api/synonyms/endpoints/synonyms.py
- solr-synonyms-api/synonyms/services/synonyms/mixins/designation.py
*#3532, Sort designations by Language:*
-Sort by Language, then by length
-Fixes related to designation variables in GetSynonymListsMixin that have to be in GetDesignationsListsMixin. In GetSynonymListsMixin we leave just prefixes, substitution, stop words
-Removed unused variables in _clean_name_words, we are sending all_designations instead of splitting in any/end (this was commented, just removing comments)
-Returning list instead of list of tuples in get_designation_any_in_name
> 3532 sort designations by language

- api/namex/resources/auto_analyse/analysis_issues.py
*#3385, Special Restricted Words Result Panel:*
-Change show_examination_button from True to False to stop showing examination button when there are just one issue.
Test case:
VANCITY PLUMBING 
VANCITY PLUMGING LTD.
> Set show_examination_button to False to show the button just when the…re is one issue, but not show when there are multiple issues.

- api/namex/services/name_request/auto_analyse/name_analysis_director.py
*#3768, Switch Response Order for Designations:*
Switch response order from 
analysis_issues_sort_order = [
AnalysisIssueCodes.ADD_DISTINCTIVE_WORD,
AnalysisIssueCodes.ADD_DESCRIPTIVE_WORD,
AnalysisIssueCodes.WORDS_TO_AVOID,
AnalysisIssueCodes.TOO_MANY_WORDS,
AnalysisIssueCodes.CONTAINS_UNCLASSIFIABLE_WORD,
AnalysisIssueCodes.WORD_SPECIAL_USE,
AnalysisIssueCodes.NAME_REQUIRES_CONSENT,
AnalysisIssueCodes.CORPORATE_CONFLICT,
AnalysisIssueCodes.DESIGNATION_NON_EXISTENT,
AnalysisIssueCodes.DESIGNATION_MISMATCH,
AnalysisIssueCodes.DESIGNATION_MISPLACED
]
to DESIGNATION_MISMATCH before DESIGNATION_MISPLACED:
analysis_issues_sort_order = [
AnalysisIssueCodes.ADD_DISTINCTIVE_WORD,
AnalysisIssueCodes.ADD_DESCRIPTIVE_WORD,
AnalysisIssueCodes.WORDS_TO_AVOID, …
> Switch issue sort order to first misplaced, then mismatch.

- api/namex/resources/auto_analyse/analysis_issues.py
- api/namex/services/name_processing/name_processing.py
- api/namex/services/name_request/auto_analyse/name_analysis_director.py
- api/namex/services/name_request/auto_analyse/name_analysis_utils.py
- api/namex/services/name_request/auto_analyse/protected_name_analysis.py
- api/namex/services/name_request/name_analysis_builder_v2/name_analysis_builder.py
- api/tests/python/end_points/auto_analyse/protected_names/test_auto_analyse_invalid_np_bc.py
- api/tests/python/namex_services/name_processing/test_name_processing.py
- solr-synonyms-api/synonyms/endpoints/synonyms.py
- solr-synonyms-api/synonyms/services/synonyms/synonym.py
*#3688, Fix name cleaning bugs discovered when running pytests:*
- Change to upper case responses shown in FE
- Change special and words to avoid to show in FE as compound when they are more than one word such as "BIG BROS" instead of showing "BIG","BROS"
- Change response from None to ProcedureResult type for well_formed, unclassified words and check limit.
- Removed unused misplaced_any_designation and misplaced_all_designation
- Refactoring in clean name to avoid calling regex-prefix and remove_french twice for each request.
- Fixed remove_french to split the name as long as there is a designation before the slash or hyphen
- Remove numbers inside parenthesis with anything else inside such as (YR 2008) or (SOMETHING 2008).
- Exclude designations to be …
> 3688 v2 fix name cleaning bugs discovered pytests

- api/namex/resources/auto_analyse/analysis_options.py
- api/namex/resources/auto_analyse/paths/bc_name_analysis/bc_name_analysis_response.py
- api/namex/services/name_request/auto_analyse/abstract_name_analysis_builder.py
- api/namex/services/name_request/auto_analyse/protected_name_analysis.py
- api/namex/services/name_request/builders/name_analysis_builder.py
- api/tests/python/end_points/auto_analyse/protected_names/test_designation_mismatch_one_word_with_hyphen_request.py
- api/tests/python/end_points/auto_analyse/protected_names/test_end_designation_more_than_once.py
- solr-synonyms-api/synonyms/services/synonyms/synonym.py
*#3975, Issue type designation more than one:*
- Add a type to setup (type="two_designations")
- Only include the issue type when all designations are valid for the entity type
- Update test cases for issue type designation more than one.
- 
> 3975 issue type designation more than one

- api/namex/services/nro/change_nr.py
This is to accommodate the release on June 26th on the updated request_instance table.  This requires the hom_juris_num to be present in the sql going back to oracle for an edit in Namex.
> removed feature flag in request_instance for home_juris_num

- api/namex/constants/__init__.py
- api/namex/resources/auto_analyse/analysis_options.py
- api/namex/resources/auto_analyse/paths/bc_name_analysis/bc_name_analysis.py
- api/namex/resources/auto_analyse/paths/xpro_name_analysis/issues/add_descriptive_word.py
- api/namex/resources/auto_analyse/paths/xpro_name_analysis/issues/add_distinctive_word.py
- api/namex/resources/auto_analyse/paths/xpro_name_analysis/issues/contains_unclassifiable_word.py
- api/namex/resources/auto_analyse/paths/xpro_name_analysis/issues/contains_words_to_avoid.py
- api/namex/resources/auto_analyse/paths/xpro_name_analysis/issues/corporate_name_conflict.py
- api/namex/resources/auto_analyse/paths/xpro_name_analysis/issues/designation_mismatch.py
- api/namex/resources/auto_analyse/paths/xpro_name_analysis/issues/designation_misplaced.py
- api/namex/resources/auto_analyse/paths/xpro_name_analysis/issues/designation_non_existent.py
- api/namex/resources/auto_analyse/paths/xpro_name_analysis/issues/incorrect_category.py
- api/namex/resources/auto_analyse/paths/xpro_name_analysis/issues/name_requires_consent.py
- api/namex/resources/auto_analyse/paths/xpro_name_analysis/issues/too_many_words.py
- api/namex/resources/auto_analyse/paths/xpro_name_analysis/issues/word_special_use.py
- api/namex/resources/auto_analyse/paths/xpro_name_analysis/xpro_name_analysis.py
- api/namex/resources/auto_analyse/paths/xpro_name_analysis/xpro_name_analysis_response.py
- api/namex/services/name_request/builders/name_analysis_builder.py
- api/namex/services/nro/change_nr.py
- api/tests/python/end_points/auto_analyse/common.py
- api/tests/python/end_points/auto_analyse/protected_names/test_request_actions_bc.py
- nro-legacy/sql/object/names/namex/procedure/sync_consumed_names.sql
- nro-legacy/sql/release/202006XX_namex-proc/names/namex/create.sql
*#4087, Few Tweaks to line up the Front-End and Back-End:*
Changes in protect names:
- Return non_existent_designation issue when the entity type has designation. Otherwise, do not return it.
- In protected name analysis, add request_action CHG, DBA for location ='BC' 
Changes in XPRO names:
- If request action = MVE and location != BC, then go to protected auto analyse.
- if request action != MVE and location !=BC, then go to xpro auto analyse.
> 4087 few tweaks line up fe and be

- api/namex/models/request.py
- api/namex/services/name_request/auto_analyse/abstract_name_analysis_builder.py
- api/namex/services/name_request/auto_analyse/name_analysis_director.py
- api/namex/services/name_request/auto_analyse/name_analysis_utils.py
- api/namex/services/name_request/auto_analyse/protected_name_analysis.py
- api/namex/services/name_request/builders/name_analysis_builder.py
- api/tests/python/end_points/auto_analyse/protected_names/test_add_descriptive_word_base_request.py
- api/tests/python/end_points/auto_analyse/protected_names/test_add_distinctive_word_base_request.py
- api/tests/python/end_points/auto_analyse/protected_names/test_corporate_name_conflict_exact_match_request.py
*3921 #, Add Search Conflicts to Well Formed Name:*
Names with word under the same category provided to check_name_is_well_formed function search for conflicts before sending a response for either ADDING DESCRIPTIVE or ADDING DISTINCTIVE. If the search conflicts execution ends up with a conflict then this would be the response of check name is well formed and continue the analysis. Then, search conflicts process will be skip. The final response includes the conflict found in check_name_is_well_formed.
> 3921 v2 add search conflicts to well formed name

- api/namex/models/request.py
ValidSources enum causes an psycopg error cant adapt on the event listener when you have to include namex-api as a requirement in another job.  This solves that problem.
> fixed-valid-sources-for-jobs

- api/namex/services/nro/add_nr.py
- api/namex/services/nro/change_nr.py
- api/namex/services/nro/oracle_services.py
A temporary workaround to solve oracle namesd connection issue until a permanent solution can be created.  One will be to update the add_nr and chnage_nr for better error handling/trapping as well as multiple commits.  May use the return syntax as well the server SDU size needs to be increased and the client connection we also need to add an SDU parameters in the cx_oracle connection.
> temp fix fo oracle probelm so we dont keep creating bad data

- api/namex/resources/name_requests/name_request.py
pointing to the service rather than the model so wasnt handling REH/REN request_actions
> fixed reapply to extend the expiry date for REH and REN request actions

- api/namex/resources/auto_analyse/analysis_options.py
- api/namex/resources/auto_analyse/paths/xpro_name_analysis/xpro_name_analysis_response.py
*4748 #, Update Conflict Messaging for Specific EntityTypes:*
Additional message for XPRO analysis considering Entity Types different to 'CR', 'XUL' and  'RLC' to refer to this new message:
"There is an existing BC entity with a similar name therefore you must use a different name in BC. "
"This may require you to register the new name in your home jurisdiction first before proceeding here."
Entity Types equal to 'CR', 'XUL' or  'RLC'  refer to the same message:
"Extra provincial or registration of a foreign entity in BC requires use of an Assumed Name when there is an existing BC entity with a similar name."
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache …
> 4748-Update Conflict Messaging for Specific Entity Types (XPRO).

- api/namex/services/nro/request_utils.py
- nro-legacy/sql/object/names/namex/view/request_vw.sql
- nro-legacy/sql/release/202009XX_request_vw/names/namex/create.sql
Impacts NRO-Extractor, Get, GET Next, HOLD in Namex.  Adds the home_juris_num from oracle request_instance to postgres requests for completeness.
> 4398 home juris num

- api/namex/services/nro/request_utils.py
To fix psycopg2.ProgrammingError: can't adapt type 'ValidSources' in the extractor
> fix Valid Sources Issue on postgres insert

- api/namex/services/name_request/auto_analyse/xpro_name_analysis.py
*hotfix/Missing Stand-alone words in XPRO names:*
Missing parameter in get_classification located in utils. Added stand-alone words for XPRO names.
> XPROs missing stand-alone words.

- api/namex/services/name_processing/name_processing.py
- api/namex/services/name_request/auto_analyse/mixins/get_word_classification_lists.py
- api/namex/services/name_request/auto_analyse/name_analysis_utils.py
- api/namex/services/name_request/builders/name_analysis_builder.py
*5070 #, Numbers Getting Stripped Out AS DIST When in the First Position:*
Fixed regex to include numbers in the tokenized version of  names used by configure_issue.
Discarded conflict when name has an additional descriptive in the same group of synonym and additional distinctive.
Renamed a function (typo issue)
> 5070 numbers getting stripped out

- api/namex/services/name_request/builders/name_analysis_builder.py
- solr-synonyms-api/synonyms/services/synonyms/synonym.py
*5057 #, Handle H2 everywhere in name:*
- Remove the application of any transformation to abbreviations made of numbers and names
- Additional check for ensuring the different descriptive found in new name is not in the original descriptive list of conflicted name. 
> 5057 handle h2 everywhere in name

- api/namex/resources/name_requests/abstract_solr_resource.py
- api/namex/resources/name_requests/name_request.py
Fixes the bug.  When a TEMP_NR is cancelled it must also be cancelled in solr.  It does not have anything in oracle but does in sorl for cancelled cond-reserve and reserved NRs that are a corp entity type.  The timeout on the front-end when the user sits on the screen to complete applicant info and does not click Continue & Pay.  They have 5 mins and then it all gets cancelled.
> Fix solr cancel

- api/namex/models/virtual_word_condition.py
- api/namex/models/word_classification.py
- api/namex/services/name_processing/name_processing.py
- api/namex/services/name_request/auto_analyse/mixins/get_designations_lists.py
- api/namex/services/name_request/auto_analyse/name_analysis_director.py
- services/auto-analyze/auto_analyze/__init__.py
- services/auto-analyze/auto_analyze/analyzer.py
*5336 #, Quart Service move preparation tasks:*
- Move a level up prepare data function to decouple from set_name function, we are just passing the values collected from prepare_data.
- Close sessions to avoid timeout in database
- Add logging in auto-analyze service
> 5336 quart service move preparation tasks

- api/namex/services/name_request/auto_analyse/mixins/get_word_classification_lists.py
- api/namex/services/name_request/auto_analyse/name_analysis_utils.py
*5117 #, ASSETS Causes Strange Behaviour:*
When checking for well formed names, the dictionary passed containing the classification needs to be the original one, not the one processed for search conflicts.
> 5117: ASSETS-CausesStrangeBehaviour

- api/namex/services/name_request/auto_analyse/name_analysis_utils.py
- api/tests/python/end_points/auto_analyse/protected_names/test_corporate_name_conflict_same_classification.py
*5279 #, Handle Name Where All Words Are Classified as All Dist or All Desc:*
- Modify get_classification to replace for descriptive the last word if all words are distinctive. In the same way, replace for distinctive the first word if all words are descriptive.
> 5279/Handle names with same category and longer than two words in length.

- api/namex/services/name_request/builders/name_analysis_builder.py
- api/tests/python/end_points/auto_analyse/protected_names/test_name_requires_consent_compound_word_request.py
*I5046 #, Handle Consent Word Phrases:*
- Exhaust all possible words requiring consents, not just the first occurrence.
> 5406 handle consent word phrases

- api/namex/models/request.py
- api/namex/services/name_request/auto_analyse/name_analysis_utils.py
- api/namex/services/name_request/auto_analyse/protected_name_analysis.py
- api/namex/services/name_request/auto_analyse/xpro_name_analysis.py
- api/namex/services/name_request/builders/name_analysis_builder.py
- api/tests/python/end_points/auto_analyse/protected_names/test_corporate_name_conflict_request.py
- services/auto-analyze/auto_analyze/analyzer.py
- solr-synonyms-api/synonyms/services/synonyms/synonym.py
*bcgov/entity#5593*
- Retrieve conflicts that include distinctive as second token followed by descriptive. Before just the first token was considered a valid distinctive.
- When getting synonyms do not include stand-alone words to avoid mixing them with regular synonyms.
- Name analysis was changed to be over the full name instead of dropping synonyms in the same category.
- Removing duplicated letters is done after getting synonyms.
- Added test cases for distinctive after first place
Test 1:
Test 2:
Test 3:
Test 4:
Test 5:
Test 6:
Regression test:
> 5593 change query search distinctives

- .github/workflows/auto-analyze-cd.yml
Update for deprecating set-env command of GHA.
> Update for deprecating set-env command of GHA.

- api/namex/services/name_request/auto_analyse/protected_name_analysis.py
- api/namex/services/name_request/auto_analyse/xpro_name_analysis.py
- Running NameX testing requires to disable code invoking search exact match for queue conflicts. 
> Disable exact match for queue conflicts

- api/namex/services/name_request/auto_analyse/name_analysis_utils.py
- api/tests/python/end_points/auto_analyse/protected_names/test_corporate_name_conflict_request.py
*bcgov/entity#5678*
Do not remove duplicated letters when all token contains the same letter. For instance, `AAA` should be kept as it is instead of transforming to just `A`.
Added corresponding test cases:
> 5678 modify duplicated letters

- api/requirements.txt
- api/requirements/prod.txt
- add dataclasses for python < 3.7
> add dataclasses module for python < 3.7

- api/namex/services/name_request/auto_analyse/name_analysis_utils.py
- api/namex/services/name_request/auto_analyse/protected_name_analysis.py
- api/namex/services/name_request/auto_analyse/xpro_name_analysis.py
- api/namex/services/name_request/builders/name_analysis_builder.py
- api/tests/python/end_points/auto_analyse/protected_names/test_corporate_name_conflict_request.py
- services/auto-analyze/src/auto_analyze/analyzer.py
- solr-synonyms-api/requirements/prod.txt
- solr-synonyms-api/synonyms/services/synonyms/synonym.py
*bcgov/entity#5687:*
- Stemming distinctives and descriptives in dictionaries
- Search in synonyms for original word, if no result stemming word
- Adding gerund form for distinctives
- Deleted additional_dist_desc function, it is not longer needed after name examination session with Genevieve.
- Added test cases.
Regression Test:
Test 1 (plurals):
Test 2 (original distinctive - Mechanical in the same category as plumbing):
> 5687 stem distinctive

- api/namex/services/name_request/auto_analyse/name_analysis_utils.py
- services/auto-analyze/src/auto_analyze/analyzer.py
*bcgov/entity#5820*
Get back the original behavior of check_well_formed name while getting the classification logic for conflict names.
> keep classification in well-formed name.

- api/namex/constants/__init__.py
- api/namex/services/name_request/name_request_state.py
*Issue /bcgov/entity#5746
- REAPPLY is not needed for MVP
- Removed Refund from Inprogress
> REAPPLY is not needed for MVP

- api/namex/resources/auto_analyse/analysis_options.py
- api/namex/resources/auto_analyse/analysis_response.py
- api/namex/resources/auto_analyse/issues/__init__.py
- api/namex/resources/auto_analyse/issues/abstract/analysis_response_issue.py
- api/namex/resources/auto_analyse/issues/designation_removal.py
- api/namex/resources/auto_analyse/paths/bc_name_analysis/bc_name_analysis_response.py
- api/namex/resources/auto_analyse/paths/bc_name_analysis/issues/__init__.py
- api/namex/resources/auto_analyse/paths/bc_name_analysis/issues/designation_removal.py
- api/namex/resources/auto_analyse/utils.py
- api/namex/services/name_request/auto_analyse/__init__.py
- api/namex/services/name_request/auto_analyse/name_analysis_director.py
- api/namex/services/name_request/builders/name_analysis_builder.py
*bcgov/entity#5527:*
- Unprotected names are asked to remove designations when entity type is one of the following:
Sole Propietorship
Doing Business As
General Partnership
- The following unprotected entity types are checked for correct designation:
Limited Partnership
Limited Liability Partnership
- Well formed name analysis not showing missing distinctive or descriptive for Unprotected Entity Types. When just one word, search conflicts does not have to run.
> 5527: Sole Props/DBAs, LLP, BC LP/GP apply expro rules

- api/namex/resources/auto_analyse/paths/xpro_name_analysis/xpro_name_analysis_response.py
*bcgov/entity#5919*
Removed assumed name Option in search conflict for approved and queue conflicts.
> 5919/Removed Assumed Name from corporate and queue conflicts for XPRO

- api/namex/models/request.py
*Issue #, bcgov/entity#6082
removed the Priority code from the sort order of the select.
> remove Priority from getting the oldest Draft.

- api/namex/resources/payment/payment.py
Validate the NR state before cancel and refund. Cancel and Refund should happen only for NRs in DRAFT state
> Check NR state before request and refund

- api/namex/resources/payment/payment.py
*Issue #6047
UI was receiving a response code of 0 from the api... I followed the path, and found this path where there was no exception thrown, but the api didn't receive an expected status code. In this case I print the status code, and return an error to the UI
> 6047 - handle unexpected status case

- .gitignore
- api/namex/constants/__init__.py
- api/namex/resources/requests.py
- api/namex/utils/common.py
- api/tests/python/end_points/common/utils.py
- api/tests/python/end_points/test_namex_search.py
*Issue #:* /bcgov/entity#7433
*Description of changes:
* Added `submittedStartDate` and `submittedEndDate` search filters to `.../api/v1/requests` url.  
* Added test for `submittedStartDate` and `submittedEndDate` search filters
* Added files to ignore in `.gitignore`
* Added endpoint testing related utility functions under endpoint tests folder
> 7433 Add submitted start/end date filter to requests search endpoint

- api/namex/resources/name_requests/name_request.py
- api/namex/resources/payment/payment.py
*Issue*:
bcgov/entity#7812
bcgov/entity#7818
> 7812, 7818 skip refund for routingSlip and waiveFee, remove staff auth header if no option provided

- api/namex/services/payment/models/__init__.py
* Added `details` field to `PaymentInvoice` class
> Fix issue with serializing new details field in payment service response 

- api/namex/models/user.py
- api/namex/resources/requests.py
> 6033 allow system user to patch nr, required to consume nr from entity-filer

- api/namex/models/request.py
- api/namex/resources/requests.py
previousRequestId comes in as an integer so schema check was failing on edit
- changed schema value to int
- removed schema check from edit since we are trying to move away from ma and there could be other edge cases
> fixed schema, removed check from namex edit

- api/namex/resources/payment/payment.py
- api/namex/services/payment/client/__init__.py
- When folioNumber is coming as empty string, it doesn't get removed from headers. This causes NR code to not creating a service account token which in turn causes 401 for payment calls.
-  https://github.com/bcgov/namex/blob/main/api/namex/resources/payment/payment.py#L306 : If value is empty string; doesn't reach the if section and headers doesn't get deleted.
- https://github.com/bcgov/namex/blob/main/api/namex/services/payment/client/__init__.py#L197 : Since the headers is not empty, it doesn't create a service account token.
> Fixing issue with NR invoice creation failure, when folioNumber is empty string

- api/namex/services/statistics/__init__.py
- api/namex/services/statistics/wait_time_statistics.py
- api/tests/python/end_points/common/utils.py
- api/tests/python/end_points/statistics/common.py
- api/tests/python/end_points/statistics/test_statistics.py
*Issue #:* /bcgov/entity#6968
* Update wait time calculation logic in `statistics` endpoint to mirror NRO logic which is to use the oldest unexamined NR minus weekends
> 6968 Update wait time calculation logic to mirror NRO

- api/setup.cfg
*Issue #, if available:* N/A
duplicate pylint in setup was causing make cmd errs
> deleted duplicate pylint

- api/namex/resources/events.py
- api/tests/python/end_points/test_events.py
*Issue #: /bcgov/entity#8247
* updated get events endpoints to include comment value for staff comment events
* added test for testing staff comment events
> 8247 Update get events endpoint to return comment value for staff comments event type

- jobs/nr-day-job/devops/vaults.json
> 7388 new valult `nr-day-job` instead of using nats-emailer

- api/namex/services/queue.py
- services/namex-pay/config.py
- services/namex-pay/requirements.txt
- services/namex-pay/src/namex_pay/config.py
- services/namex-pay/src/namex_pay/worker.py
- services/namex-pay/tests/conftest.py
- services/namex-pay/tests/unit/test_worker.py
*Issue:  bcgov/entity#8488*
- Added config; 
- Initialized the queue;
- Updated the stan client_id everytime nats reconnects; 
- Initalized QueueService with a new event loop; 
- Added nest_asyncio to tests for the queue services work properly.
> 8488- Updates for new NATS messages and Resubmit payment action

- api/namex/resources/events.py
> 8554 fix transaction history for resubmit

- api/namex/services/payment/models/__init__.py
- api/tests/python/services/payment/__init__.py
- api/tests/python/services/payment/test_models.py
*Issue #, if available:* 
https://github.com/bcgov/entity/issues/8676
- Ignore unknown attributes in payment-requests response json.
> 8676: Ignore unknown attributes in payment-requests response json.

- services/solr-names-updater/src/solr_names_updater/worker.py
- services/solr-names-updater/tests/unit/__init__.py
- services/solr-names-updater/tests/unit/test_names_processor.py
- services/solr-names-updater/tests/unit/test_possible_conflicts_processor.py
*Issue #: bcgov/entity#8793
* Update `CONSUME` state processing logic for an NR
* Update tests for `CONSUME` state
> 8793 Update NR CONSUMED state change processing logic

- api/namex/models/name.py
- jobs/nr-day-job/nr_day_job.py
- To avoid nested loop error, making nr day job as sync function (This will allow queue.py to create a new event loop)
- When there is a stateCd change, the request model pushes a state change queue synchronously and to do that queue.py uses an event loop
> 8721 refactor nr day job to fix event loop already running issue

- api/namex/models/name.py
- added check that corpNum is not None, so that CONSUMED is not set.
Error -> extractor.app - DEBUG - [name.py:146] - moved to CONSUMED state **None**
> added a check that the corpNum is not None

- services/solr-names-updater/Makefile
- services/solr-names-updater/src/solr_names_updater/worker.py
- services/solr-names-updater/tests/unit/__init__.py
- services/solr-names-updater/tests/unit/test_names_processor.py
- services/solr-names-updater/tests/unit/test_possible_conflicts_processor.py
- services/solr-names-updater/tests/unit/test_worker.py
*Issue # https://github.com/bcgov/entity/issues/8810
When nr is processed through the solr names updater bypass the posts to SOLR database functions if the company entity_type_cd is FR (Sole prop) or GP (General Partnership)
> 8810 dont update solr names DB for SP and GP

- services/solr-names-updater/src/solr_names_updater/version.py
- services/solr-names-updater/src/solr_names_updater/worker.py
- services/solr-names-updater/tests/unit/test_names_processor.py
- services/solr-names-updater/tests/unit/test_possible_conflicts_processor.py
*Issue #8810 
When nr is updated or inserted, a listener executes code to update queue services Do not call this function if the company entity_type_cd is FR (Sole prop) or GP (General Partnership)
> 8810_sp_gp_nr_approvals_showing_as_conflicts

- jobs/nro-update/nro/nro_datapump.py
- jobs/nro-update/requirements.txt
- jobs/nro-update/tests/test_nro_datapump.py
*Issue #:* /bcgov/entity#10139
- Call NameRequestService.create_expiry_date() in place of local function. This is in the job that runs after a NR is approved, and which sets the expiration datetime.
> 10139 - Use NameRequestService.create_expiry_date()

- api/namex/resources/payment/payment.py
- api/namex/services/name_request/name_request.py
- jobs/nro-update/nro_update.py
*Issue #bcgov/entity/#7087, if available:*
the return value from get_expiry_days needs to be converted to integer to fix TZ string issue in create_expiry_date
> 7087_restore_reinstate_bug fix

- api/namex/resources/payment/payment.py
- api/namex/services/name_request/name_request.py
- api/tests/python/services/name_request/test_abstract_name_request.py
*Issue #:/bcgov/entity#11256
Expiration_date fix when Request Action Cd is null, then we check Request Type to set expiry days
> 11256_restore_reinstate_action_cd_null_fix

- colin-api/src/colin_api/resources/v1/corporations.py
*Issue #, [Namex API: shouldn't crash (500) on invalid Corp Num](https://github.com/bcgov/entity/issues/15026)
[entity #15026](https://github.com/bcgov/entity/issues/15026)
I traced the issue to colin-api, where in the logs you would get:
```
incorp_reg_addr_id = incorp_addr_ids[0][0]
IndexError: list index out of range
```
Looking at this I have more questions than answers. I could observe the 500 error only in dev environment and not test/prod, where in the latter we would be getting a 404 instead.
This would fix the 500 in dev, but is this the desired behavior (rather than exception message.. although I do feel uneasy using exceptions for index out of range errors)
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …
> check if nr was found in db

- jobs/notebook-report/Makefile
- jobs/notebook-report/notebookreport.py
- jobs/nr-duplicates-report/notebookreport.py
*Issue #, if available:* 2247
All notebook reports (including Namex, LEAR, PAY notebook reports) were sent but didn't deliver to the receivers. The reason for this is that the contents in the email body were filter by the email server. Need to update codes to fix this issue.
[To fix all notebook reports Sent but not delivered Issue#2247](https://app.zenhub.com/workspaces/entity-5bf2f2164b5806bc2bf60531/issues/gh/bcgov-registries/ops-support/2247)
> To fix all notebook reports Sent but not delivered Issue#2247

- jobs/nro-update/nro/nro_datapump.py
*Description of changes: nro-update job is currently broken in main. job runs result in errors:
2023-05-11 23:08:09,608 - nro.app - ERROR in nro_update:nro_update.py:96 - <module>: 'InstrumentedList' object has no attribute 'all'
InstrumentedList is a SQLAlchemy iterable object. Removing .all() causes jobs to succeed.
> fix 'InstrumentedList' object has no attribute 'all'

- jobs/nr-duplicates-report/daily/nr-duplicates.ipynb
*Issue #, if available:* Fixed spreadsheet size over limited by google
Keep the spreadsheet for one month only, so it wouldn't cause the oversize issue.
> Fixed spreadsheet size over limited by google #2724

- jobs/nr-day-job/devops/vaults.json
*Description of changes: nr-day-job in openshift was missing nats related secrets, so github actions deployment would break the job, since all necessary secrets would not be pulled from 1password
> add missing secrets

- api/namex/analytics/solr.py
- api/namex/resources/requests.py
- api/tests/python/end_points/test_namex_search.py
- api/tests/python/solr/test_query_string.py
> 16714 nr search

- api/report-templates/emails/approved.md
- api/report-templates/emails/conditional.md
- api/report-templates/emails/consent.md
- api/report-templates/emails/rejected.md
*Description of changes:* change approval letter to tier 1 and rest to tier 2
Hi Patrick,
Can we please keep Maximus’s number for Receipt, Renewal, Upgrade, Expiry soon, Expiry? Is it possible to differentiate between and approved letter and a rejection letter? I think we should likely keep the Tier 2 number on the rejection and consent letters if possible.
Megan Fedora (she/her)
Manager, Registries Operations
BC Registries and Online Services
Service BC 
Ministry Citizens’ Services 
T 778-671-9262
Email: [Megan.Fedora@gov.bc.ca](mailto:Megan.Fedora@gov.bc.ca)
> Another email design sync

- api/namex/resources/name_requests/report_resource.py
- api/report-templates/emails/approved-so.md
- api/report-templates/emails/conditional-so.md
- api/report-templates/nameRequest.html
- api/report-templates/template-parts/name-request/nrDetails.html
*Issue #18240 https://github.com/bcgov/entity/issues/18240 
approved and conditionals
> 18240-NR Letters-Society

- jobs/nr-day-job/nr_day_job.py
https://github.com/bcgov/entity/issues/18567
update queries:
1. update the query to pick up the nrs to be expired:
a. cast expiration_date in the query to be a Date type, so that the time part aligns up CURRENT_DATE, which is 0:00
b. remove the condition: Request.notifiedBeforeExpiry == True. notified before expiry should not be a condition to expiry an NR.
2. update the query to pick up the nrs to be notified before expired
a. cast expiration_date in the query to a be Date type 
3. move notify_nr_expired() before notify_nr_before_expiry, because notify_nr_expired includes state_cd update.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license …
> 18567 update nr_day_job query

- solr-feeder/.env.sample
- solr-feeder/solr_feeder/services/colin.py
- solr-feeder/solr_feeder/version.py
*Issue #, if available:* https://github.com/bcgov/entity/issues/18039
> ops bug fix for businesses with parties with data issues

- api/namex/resources/name_requests/report_resource.py
bcgov/entity#20142
This PR undoes a change introduced in a previous PR which sent a PDF attachment with "consent received" emails.
> 20142 Revert sending an attachment with "consent received" emails

- api/namex/analytics/solr.py
*Issue #, 20344*
Based on the requirements from name examiners, I added name state filter to display only `A`(Approved) and `R`(Rejected) names on history tab.
> Added name state type filter to SOLR Query

- api/namex/analytics/solr.py
*Issue 20344, if available:*
Got SOLR Query from SOLR UI and replaced with wrong one.
> Fixed error on SOLR Query

- api/namex/models/request.py
*Issue #: [21659](https://app.zenhub.com/workspaces/names-team-board-new-655554cbddd49510027dad2e/issues/gh/bcgov/entity/21659)*
Added `Order_by` to `Request` model.
> 21659-Added Order By Choice when Retrieving a Request Record

- api/namex/services/name_request/utils.py
https://github.com/bcgov/entity/issues/22774
1. Consider 'consumed' state in state transition validation
> 22774 consider 'CONSUMED' state in state transition validation

- api/namex/resources/requests.py
some nr requested from Legancy application includes %20 after NR. e.g. 'NR%209288253', which should be 'NR 9288253'
> Create 2 new API requests for the Home Team #22774

- api/namex/constants/__init__.py
- api/namex/services/lookup/name_request_filing_actions.py
*Issue #:* bcgov/entity#23382 and bcgov/entity#24193
- renamed enums for consistency with LEAR
- regrouped mapping items for consistency
- moved some codes together
- added BECC (x2)
- added CNV codes for continued in businesses
- added comments
- moved some codes together
- spelled out "BC Limited Company" and others
- added BECC and other missing CNV codes
- added whitespace and comments
> 23382 and 24193: updated codes

- api/namex/constants/__init__.py
- api/namex/services/lookup/name_request_filing_actions.py
*Issue #:* bcgov/entity#24564
- added continued-in companies to BCProtectedNameEntityTypes enum
- updated continued-in NR types for proper dictionary search
- added special case for continued-in dictionary search
> 24564 Fixed filing actions lookup for continued in companies

- services/solr-names-updater/src/solr_names_updater/resources/worker.py
*Issue #, if available:* [zenhub 25901](https://app.zenhub.com/workspaces/names-team-board-new-655554cbddd49510027dad2e/issues/gh/bcgov/entity/25901)
The conflict is popping up twice because it is in two solr cores: the names core and the search businesses core. 
The names core is not for companies that are consumed or expired, it is only for companies that are approved or conditionally approved. Once a NR gets consumed it moves to the businesses search core in a different solr instance. 
This PR removes firms from the names core when they become consumed or expired. 
> 25901 conflict popping up twice, one for nr and one for company

- api/devops/gcp/clouddeploy.yaml
*Description of changes:* I manually increased resources for dev/test. These configs will make that resource allocation will stick next deployment.
> namex-api is running out of memory in test, default is 512MB

- jobs/notebook-report/.env.smample
- jobs/notebook-report/devops/gcp/clouddeploy.yaml
- jobs/notebook-report/src/config.py
Values pulled from env need to match what is in the vaults.gcp.env file
https://github.com/bcgov/namex/blob/main/jobs/notebook-report/devops/vaults.gcp.env#L14
> fix env var typo and prepend namex before job name

- services/emailer/src/namex_emailer/email_processors/name_request.py
*Issue #, if available:* [Zenhub 26429](https://app.zenhub.com/workspaces/names-team-board-new-655554cbddd49510027dad2e/issues/gh/bcgov/entity/26429)
- GET requests should not include a request body.
- Having a json body caused google cloud run to reject the request with a 400 bad request error.
- This resolves the issue where the emailer was unable to retrieve payment info successfully. 
> 26429: fix not receiving payment receipt email when submitting an nr

- api/namex/resources/name_requests/report_resource.py
- services/emailer/poetry.lock
*Issue #, if available: #26412*
> 26412 cont_in_magic_link_outputs

- jobs/bad-designation-notifier/src/services/email_service.py
Sending an email needs to be inside the loop when going over the recipient list. In the old implementation only the last recipient was getting an email. 
> fix incorrect indentation in bad designation notifier job

- .github/workflows/ocp-relay-cd.yml
The Ubuntu upgrade was causing this error on CD: https://github.com/bcgov/namex/actions/runs/14114530499/job/39541363726
This PR applies the same fix as was done in https://github.com/bcgov/lear/commit/3df04fcd21dcbf0d3f62442c2aa76635e4ee2694
> add ocp cli tool steps to ocp relay

- services/emailer/src/namex_emailer/email_processors/name_request.py
OpenShift did not mind when the get request had an empty JSON payload but GCP does (returns a 400 malformed request)
This code needs to be in the production NameX Emailer before NameX API moves to GCP.
> release emailer branch - get request hotfix

- api/namex/resources/requests.py
Fixes problem with returning thousands or millions of rows
> remove altering row count in search query

- services/ocp-relay/ocp_relay/services/sftp.py
- Siddarth noticed that the files uploaded to sftp were missing the .gz extension causing issues
- This PR ensures that the file includes the proper .gz extension
> sftp upload includes .gz file name extension

- services/emailer/src/namex_emailer/email_processors/nr_notification.py
Issue #: /https://github.com/bcgov/entity/issues/27414 
- The first call to `get_main_template` was causing logging errors since it doesn't have the correct values for the **before-expiry NR case** => moved this call to the else case
Logs Before:
Logs After:
> 27414 - Fix Before-Expiry NR Email Logging Error

- solr-feeder/solr_feeder/__init__.py
*Issue #, if available:* https://github.com/bcgov/entity/issues/28436
I accidentally removed registering the endpoints in the solr feeder:
https://github.com/bcgov/namex/commit/f1b4f7ed5a3fd69dde6afe695d9d44ccd75bbfef#diff-9f2335eea16c66d5898e5de3228bde6a974b2bb21d8e8b82bbe43d1a90e86227L35-L44
This puts that line back in. 
> reapply endpoint registration in solr feeder

- services/emailer/src/namex_emailer/email_processors/resend.py
- services/emailer/src/namex_emailer/resources/scheduled_email_handler.py
- services/emailer/src/namex_emailer/resources/worker.py
- services/emailer/src/namex_emailer/services/helpers.py
https://github.com/bcgov/entity/issues/28408
Using a thread pool to record events cannot guarantee that the events will be logged in the correct sequence. Although this issue is unlikely to occur, it's safer and simpler to call the event update service directly
I revert back my previous changes.
> 28408 - revert thread pool

- solr-admin-app/solr_admin/keycloak.py
- solr-admin-app/solr_admin/oidc_callback.py
*Issue #, if available:* https://github.com/bcgov/entity/issues/27245
This PR fixes an issue where users were always redirected to the home page after logging in, instead of being sent back to the page they originally tried to access. The issue was caused by the state parameter being overwritten during the OIDC callback due to overly strict sanitization. The fix ensures that only the relative path is passed in state, and adds a lightweight safety check to prevent open redirect vulnerabilities. As a result, users are now redirected back to their intended destination securely after login.
> 27245 solr-admin-app: preserve original redirect path after login

- services/emailer/src/namex_emailer/services/email_scheduler.py
*Issue #, if available:* https://github.com/bcgov/entity/issues/21835
When a schedulable cloud event comes in and gets scheduled the cloud event's ID is stored to prevent duplicates. The new cloud event sent to cloud tasks was getting a new cloud event ID but since it was passed in by reference the logic was breaking and coming back as a duplicate cloud event. 
This PR creates a deep copy of the cloud event and then updates the cloud event's id, ensuring that the new cloud event created for cloud tasks is unique and passes the idempotency test. 
> 21835 make deep copy of cloud event to ensure idempotency
