- api/app/analytics/solr.py
- api/tests/postman/namex-common.walter.postman_collection.json
*Issue #:* 620
*Description of changes:* Updated Solr query strings with new search parameters.
> Updated the Solr query strings with new search parameters #620

- api/app/models/__init__.py
- api/app/models/comment.py
- api/app/models/nwpta.py
- api/app/resources/requests.py
*Issue #, if available:*#95
*Description of changes:* fixed merge conflicts
branch sync issues
> Updated NR PUT functionality for names, comments, and nwpta.

- utils/refresh-restricted-words/.env
Added missing .env file for csv import.
> Added missing .env file for csv import.

- api/Jenkinsfile
> updating jenkins notification

- nro-extractor/requirements.txt
> fixed change from bad merge

- api/namex/resources/requests.py
*Issue #, if available:* #582
Added edit functionality for Previous NR, with conversion to legacy RequestId and PreviousRequestId fields.
> Added edit functionality for Previous NR.

- nro-extractor/api/endpoints/requests.py
- nro-extractor/requirements/prod.txt
*Issue #, if available:* NA
*Description of changes:* adding some manual error checking
> chasing postgres error under load

- api/tests/python/conftest.py
*Issue #, if available:* #123 
> closes #123 py.test:conf drops all sequences from the db

- api/migrations/versions/b36c2a0baff8_change_corpnum_int_to_string.py
- api/namex/models/request.py
- api/namex/resources/requests.py
*Issue #, if available:* #582
Changed corpNum from integer to string; added validation check to NR Details.
> Changed corpNum from integer to string; added validation check to NR Details.

- api/namex/models/request.py
Bug fix - Request PUT not working due to error in call to validNRFormat(),
> Bug fix - Request PUT not working due to error in call to validNRFormat().

- nro-extractor/api/__init__.py
- nro-extractor/api/endpoints/requests.py
> more chasing postgres errors - setting pool to pessimistic

- nro-extractor/Jenkinsfile
> nro-extractor pipeline work

- api/setup.py
> unwinding install woes

- nro-extractor/Jenkinsfile
> add missing icons to pipeline

- api/MANIFEST.in
- api/README.md
- api/setup.py
- nro-extractor/Jenkinsfile
> adding manifest in hopes that non-dist setup will pickup reqs

- api/requirements/prod.NoVer.txt
- api/requirements/prod.txt
> remove spaces and unused imports

- api/Jenkinsfile
> updating slack msg

- api/setup.py
> Setup.py havc to get around module imports, need this fixed for Postgres load testing

- api/namex/__init__.py
- api/namex/models/request.py
- api/namex/nro_services/oracle_services.py
- api/namex/resources/requests.py
- api/pytest.ini
- api/tests/python/models/test_request.py
- nro-extractor/api/endpoints/requests.py
- nro-extractor/config.py
*Issue #, if available:* bcgov/name-examination#557
*Description of changes:* part of series of changes to support setting the status in NRO when getting the nest request to work on
> 557 nro status

- api/Jenkinsfile-Runtime
- api/namex/resources/requests.py
> adding more debug stmnts

- api/Jenkinsfile
- api/tests/postman/namex-pipeline-test.postman_collection.json
echo change on Jenkinsfile
newman tests:
- more tests added for dev
- pm collection added for test
> newman tests for namex pipeline update

- api/run_tests.sh
*Issue #, if available:* bcgov/namex-examination#572
*Description of changes:* script to run py.test on the container / Jenkins Pipeline
> run script to execute py.test on the linux based container

- api/config/config.py
- api/namex/resources/requests.py
- nro-extractor/api/__init__.py
- nro-extractor/api/endpoints/requests.py
- nro-extractor/config.py
> #557 - partial - fixed the db session setup

- api/namex/analytics/solr.py
- api/namex/resources/document_analysis.py
- nro-extractor/api/endpoints/requests.py
> fixed typo in method call

- api/namex/analytics/solr.py
*Issue #, if available:* n/a - testing manual searchisms
added a space between name: {name} in the Solr queries
> added a space between name: {name} in the Solr queries

- nro-extractor/api/endpoints/requests.py
*Issue #, if available:* n/a - testing manual searchisms
added a space between name: {name} in the Solr queries
> adding PUT to the allowed nro-extracts

- nro-extractor/api/endpoints/requests.py
- nro-extractor/logging.conf
*Issue #, if available:* 557
allowing for bad data from NRO, by not adding segments that are missing.
skip segments by checking if they are missing first
> allowing for bad data from NRO, by not adding segments that are missing.

- api/Jenkinsfile
IMAGE_NAME changed to IMAGE_RUNTIME_NAME in test deploy stage
> namex-pieline test deploy image name change

- api/namex/models/request.py
- api/namex/resources/requests.py
All changes needed for reset furnished + other fields done.
What I'm still working on:
- applicants and names not updating %100 properly
- error checks/handling additions
> requests PUT update

- api/namex/resources/requests.py
*Issue #, if available:* #718
Added 400 error codes missing from some responses in Request PUT.
> Added 400 error codes missing from some responses in Request PUT.

- api/namex/resources/requests.py
> adding get-next to also do a 206

- api/namex/resources/requests.py
> tracking search bug that only happens in non-prod envs

- api/namex/models/__init__.py
- api/namex/models/request.py
- api/namex/resources/requests.py
> chasing error in search - commit to have run in bad environment

- api/namex/models/applicant.py
- api/namex/models/request.py
- api/namex/resources/requests.py
Bug fix - submit date and unnecessarily required fields causng PUT error
Cannot just pop off errors, they prevent add of data via model schema.
> Bug fix - submit date and unnecessarily required fields causng PUT error

- api/tests/postman/namex-pipeline-dev.postman_collection.json
- api/tests/postman/namex-pipeline-test.postman_collection.json
> postman pipeline test update

- api/namex/resources/requests.py
*Issue #, if available:* #653
Took out unnecessary checks for invalid dates; added nwpta date.
> Took out unnecessary checks for invalid dates; added nwpta date.

- api/namex/models/request.py
Frontend changes include displaying the latest comment in the search table
> comments included in search return

- nro-update/openshift/templates/cron-nro-update.yml
- nro-update/run.sh
*Issue #, if available:* bcgov/name-examination/424
Adding the cronjob for the nro-updater
> cronjob for the nro-updater

- docs/developer.md
- docs/developer.pycharm.md
- solr-admin-app/app.py
- solr-admin-app/config.py
- solr-admin-app/docs/readme.md
- solr-admin-app/model/user.py
- solr-admin-app/monkeypatch.py
- solr-admin-app/requirements.txt
- solr-admin-app/solr_admin/__init__.py
- solr-admin-app/solr_admin/keycloak.py
- solr-admin-app/solr_admin/views/synonym_view.py
*Description of changes:* Added the authentication component to the solr-admin-app.
> Added SSO authentication to the solr-admin-app. #590

- solr-admin-app/database/database_create.md
- solr-admin-app/docs/readme.md
- solr-admin-app/monkeypatch.py
- solr-admin-app/solr_admin/__init__.py
- solr-admin-app/solr_admin/models/synonym.py
- solr-admin-app/solr_admin/models/synonym_audit.py
- solr-admin-app/solr_admin/templates/synonyms_create.html
- solr-admin-app/solr_admin/templates/synonyms_edit.html
- solr-admin-app/solr_admin/views/synonym_audit_view.py
- solr-admin-app/solr_admin/views/synonym_view.py
*Description of changes:* Added audit logging.
> Solr admin

- solr-admin-app/config.py
- solr-admin-app/docs/readme.md
- solr-admin-app/openshift/solr-admin-app-build.param
- solr-admin-app/openshift/solr-admin-app-deploy.DEV.param
- solr-admin-app/openshift/solr-admin-app-deploy.TEST.param
- solr-admin-app/openshift/templates/solr-admin-app-build.json
- solr-admin-app/openshift/templates/solr-admin-app-deploy.json
*Description of changes:* Added the configuration files for OpenShift, and added missing config for an OIDC bug.
> Added OpenShift config and fixed OIDC bug. #590

- solr-admin-app/config.py
*Description of changes:* Another fix for the OIDC bug, works locally but not on OpenShift.
> New fixed for OIDC bug. #590

- solr-admin-app/config.py
- solr-admin-app/docs/readme.md
- solr-admin-app/requirements.txt
- solr-admin-app/solr_admin/solr/__init__.py
- solr-admin-app/solr_admin/views/synonym_view.py
*Description of changes:* added automatic reloading of Solr cores.
> Added automatic reloading of Solr cores #590

- solr-admin-app/docs/readme.md
- solr-admin-app/openshift/solr-admin-app-deploy.DEV.param
- solr-admin-app/openshift/solr-admin-app-deploy.TEST.param
- solr-admin-app/openshift/templates/solr-admin-app-deploy.json
*Description of changes:* Added the configuration so solr-admin-app knows where the Solr instance is.
> Updated OpenShift config to include Solr location. #590

- api/namex/resources/requests.py
*Issue #, if available:* #764
*Description of changes:* 
Make search filters case-insensitive - NR #, examiner, company name.
> 764 case sensitive search

- solr/cores/names/conf/managed-schema
- solr/cores/possible.conflicts/conf/managed-schema
- solr/cores/trademarks/conf/managed-schema
*Issue #, if available:* 783
*Description of changes:* updated the managed-schema files.
> Solr configuration changes. #783

- api/namex/resources/requests.py
- nro-update/nro/nro_datapump.py
*Issue #, if available:* #686
Send decision comment (final) to NRO via updater; Update name comment in Request PUT.
> Send decision comment (final) to NRO via updater; Update name comment in

- solr/cores/names/conf/solr-data-config.xml
- solr/cores/possible.conflicts/conf/solr-data-config.xml
*Issue #, if available:* 804
*Description of changes:* Updated the Solr cores to use the new view names in the new Oracle schema available through the foreign data wrappers.
> Solr: update cores to use new FDW objects. #804

- solr-admin-app/app.py
- solr-admin-app/config.py
- solr-admin-app/docs/readme.md
- solr-admin-app/monkeypatch.py
- solr-admin-app/requirements.txt
- solr-admin-app/solr_admin/__init__.py
- solr-admin-app/solr_admin/keycloak.py
- solr-admin-app/solr_admin/models/__init__.py
- solr-admin-app/solr_admin/models/synonym.py
- solr-admin-app/solr_admin/models/synonym_audit.py
- solr-admin-app/solr_admin/solr/__init__.py
- solr-admin-app/solr_admin/views/synonym_audit_view.py
- solr-admin-app/solr_admin/views/synonym_view.py
*Issue #, if available:* 809
*Description of changes:* solr-admin-app was my first substantial work in python, and was not very pythonic. Used PEP8 as guidance to clean up the code.
> Solr: make admin app more pythonic. #809

- solr-admin-app/docs/readme.md
- solr-feeder/app.py
- solr-feeder/config.py
- solr-feeder/docs/readme.md
- solr-feeder/openshift/solr-feeder-build.param
- solr-feeder/openshift/solr-feeder-deploy.DEV.param
- solr-feeder/openshift/solr-feeder-deploy.TEST.param
- solr-feeder/openshift/templates/solr-feeder-build.json
- solr-feeder/openshift/templates/solr-feeder-deploy.json
- solr-feeder/requirements.txt
- solr-feeder/solr_feeder/__init__.py
- solr-feeder/solr_feeder/endpoints/__init__.py
- solr-feeder/solr_feeder/endpoints/feeds.py
- solr-feeder/solr_feeder/endpoints/probes.py
- solr-feeder/solr_feeder/models/__init__.py
- solr-feeder/solr_feeder/models/completed_nr.py
- solr-feeder/solr_feeder/solr.py
*Issue #, if available:* 527
*Description of changes:* added the Solr feeder api for names.
> Solr: added the feeder project. #527

- solr-admin-app/solr_admin/solr.py
*Issue #, if available:* 818
*Description of changes:* Fixed a bug with the core name regex.
> Refactored solr package into a module. #818

- solr/cores/names/conf/solr-data-config.xml
- solr/cores/names/conf/synonyms.txt
- solr/cores/possible.conflicts/conf/solr-data-config.xml
- solr/cores/possible.conflicts/conf/synonyms.txt
- solr/cores/trademarks/conf/synonyms.txt
*Issue #, if available:* 804
*Description of changes:* reverted FDW changes for now, the wrappers have not been updated yet.
> Update Solr cores to use new FDW objects. #804

- api/namex/services/nro/oracle_services.py
- colin-api/app/resources/corporations.py
- nro-extractor/api/endpoints/requests.py
- nro-legacy/sql/names/names_views.sql
- nro-legacy/sql/registry/registry_views.sql
Api's still need wrapper change for the views to work
> removed 'namex_' prefix from all views #789

- solr-feeder/solr_feeder/models/completed_nr.py
*Issue #, if available:* 527
*Description of changes:* Updated the solr-feeder to use the newly renamed view.
> Added the Solr feeder project. #527

- colin-api/app/__init__.py
- colin-api/app/resources/corporations.py
> desperate attempt to fix jwt error

- solr/cores/names/conf/managed-schema
- solr/cores/names/conf/solr-data-config.xml
- solr/cores/possible.conflicts/conf/managed-schema
*Issue #, if available:* 825
*Description of changes:* updated the PK for names to use the id.
> Synchronize config files. #825

- solr/cores/possible.conflicts/conf/solr-data-config.xml
*Issue #, if available:* 823
*Description of changes:* Renamed the corporations view as well and added the source column, so that now we're consistent.
> Created dataimport views for each core. #823

- api/namex/analytics/solr.py
- api/tests/python/solr/test_query_string.py
*Issue #, if available:* 728
*Description of changes:* Bug: the changes to the Solr API were not being URL escaped.
> Update Solr API to allow synonyms exclusion. #728

- nro-update/openshift/templates/cron-nro-update.yml
*Issue #, if available:* bcgov/name-examination#424
parameterize cron schedule so that it makes it easier to deploy to environments, as well as modify the runtime parameters
> issue 424, parameterize cron schedule

- solr/cores/trademarks/conf/managed-schema
*Issue #, if available:* 651
*Description of changes:* changed description to text_general, added category.
> Updated trademarks fields configuration. #651

- nro-update/nro_update.py
- nro-update/openshift/templates/cron-nro-update.yml
*Issue #, if available:* 424
added debug stmnts to print out the raw SQL that is happening on the pod, which in manual hacking is different than code in the repo, so chasing a bug in the toolchain
> 424 nro update sched

- nro-update/nro_update.py
> tracing image stream issues

- nro-extractor/api/endpoints/requests.py
- nro-legacy/sql/names/partner_name_system_vw.sql
- nro-legacy/sql/names/request_state_vw.sql
> fixes for part of the move to the new namex oracle schema

- solr/cores/trademarks/conf/managed-schema
- solr/cores/trademarks/conf/solr-data-config.xml
- solr/requirements.txt
- solr/trademarks/trademarks.md
- solr/trademarks/trademarks.py
*Issue #, if available:* 651
*Description of changes:* Created a python script to process the trademarks files and produce XML files more suitable for dataimport.
> Create processor for Solr trademarks data. #651

- solr/requirements.txt
- solr/trademarks/trademarks.md
- solr/trademarks/trademarks_loader.py
- solr/trademarks/trademarks_parser.py
*Issue #, if available:* 651
*Description of changes:* Reverted the trademarks loader to produce JSON. It now dumps it to file, and includes a new class for reading the file and loading into a Solr trademarks core.
> Feed Solr trademarks core. #651

- nro-legacy/sql/object/registry/namex/package/solr_pkb.sql
*Issue #, if available:* 530
*Description of changes:* Updates to the solr package for registries so that we're sending properly formatted queries.
> Final configuration for feeding corporations data. #530

- api/namex/analytics/solr.py
*Issue #, if available:* 869
*Description of changes:* Change in the boost for trademarks.
> Change Solr query for trademarks core. #869

- solr-admin-app/database/database_create.md
- solr-admin-app/database/database_create.sql
- solr-admin-app/database/synonyms.sql
- solr-admin-app/openshift/solr-admin-app-deploy.PROD.param
- solr-admin-app/solr_admin/views/synonym_view.py
- solr-feeder/docs/readme.md
- solr-feeder/openshift/solr-feeder-deploy.PROD.param
- solr/docs/build-notes.md
- solr/trademarks/trademarks_loader.py
*Issue #, if available:* 865
*Description of changes:* Added the missing param scripts for production where needed. Added some missing documentation that was needed for setting up production.
> Solr: Documentation and script updates for production deployment. (#865)

- nro-legacy/sql/release/20180918_namex/names/namex/create.sql
- nro-legacy/sql/release/20180918_namex/names/namex/create_dev.sql
- nro-legacy/sql/release/20180918_namex/names/namex/create_prd.sql
- nro-legacy/sql/release/20180918_namex/names/namex/create_tst.sql
- nro-legacy/sql/release/20180918_namex/registry/namex/create.sql
- nro-legacy/sql/release/20180918_namex/registry/namex/create_dev.sql
- nro-legacy/sql/release/20180918_namex/registry/namex/create_prd.sql
- nro-legacy/sql/release/20180918_namex/registry/namex/create_tst.sql
*Issue #, if available:* 875
*Description of changes:* Fixed errors encountered when running the scripts in dev.
> Preparation for production deployment. #875

- nro-update/openshift/templates/cron-nro-update.yml
*Issue #, if available:* #886
Changed frequency of nro_update cron job from 10 minutes to 1 minute.
> Changed frequency of nro_update cron job from 10 minutes to 1 minute.

- nro-extractor/api/endpoints/requests.py
*Issue #, if available:* bcgov/name-examination#916
load Name Request that have no submitter or names??
wtf - really? ok 8*)
> 916 load Name Request that have no submitter or names?? ok

- nro-extractor/tests/unit/test_requests.py
fixed the merge conflicts, but didn't amend it into the fix. adding as a new commit
> fixed merge conflicts that I missed in the last commit

- nro-legacy/docs/readme.md
- nro-legacy/sql/object/registry/namex/view/solr_dataimport_conflicts_vw.sql
- nro-legacy/sql/release/201809XX_solr_view/registry/namex/create.sql
*Issue #, if available:* 927
*Description of changes:* Updated the Solr conflicts view for the COLIN databases to exclude name types other than company names and numbered names. Added documentation to describe the process for working with the Oracle DBAs.
> Update Solr core view to return unique IDs. #927

- api/namex/resources/requests.py
- api/namex/services/nro/change_nr.py
- api/namex/services/nro/oracle_services.py
- nro-update/nro/app.py
- nro-update/nro/change_nr.py
- nro-update/nro_update.py
*Issue #, if available:* #424
Added to NRO services - update oracle when NR details are edited.
> 424 update nr in nro

- nro-legacy/sql/object/names/namex/package/namex_pkb.sql
*Issue #, if available:* 925
added types of transactions to send to NameX
> added types of transactions to send to namex.

- nro-legacy/sql/object/names/namex/package/solr_pkb.sql
*Issue #, if available:* 934
*Description of changes:* Update to include both cores on the delete.
> Solr: handle the RESET transaction. #934

- api/Jenkinsfile
- api/tests/postman/namex-pipeline-dev.postman_collection.json
- api/tests/postman/namex-pipeline-test.postman_collection.json
*Issue #, if available:* 928
Not completely generic - tests will still need to be manually tweaked for new NR's, but not nearly as much as before.
> postman tests updated for new test nrs -- more generic now

- api/namex/models/request.py
- api/namex/resources/requests.py
- api/namex/services/nro/change_nr.py
- api/namex/services/nro/oracle_services.py
*Issue #, if available:* #424
Changed Edit NR to only update Oracle for changed data.
Also fixed global.addressdb link to @global_address.
> Changed Edit NR to only update Oracle for changed data.

- nro-legacy/sql/release/20180926_namex/master.txt
- nro-legacy/sql/release/20180926_namex/names/namex/create.sql
*Issue #, if available:* bcgov/name-examination#925
Created a release script for the latest set of changes
> 925 created release script for test & prod

- nro-legacy/sql/object/names/namex/package/namex_pkb.sql
- nro-legacy/sql/object/names/namex/package/solr_pkb.sql
- nro-legacy/sql/object/registry/namex/package/solr_pkb.sql
- nro-legacy/sql/release/20180927_feeder_functions/names/namex/package_fix.sql
- nro-legacy/sql/release/20180927_feeder_functions/registry/namex/package_fix.sql
*Issue #, if available:* 946
*Description of changes:* Fixed bugs to do with missing return values from functions.
> Solr: fix missing function return values. #946

- api/namex/models/name.py
Changed default name designation from DRAFT (not a real designation) to null.
> Changed default name designation from DRAFT (not a real designation) to null

- api/namex/services/nro/change_nr.py
*Description of changes:* Bug fix - add new names to oracle - was erroring out when new names added in namex (choice 2 and 3) that didn't exist in Oracle.
> Bug fix - add new names to oracle

- nro-legacy/sql/object/names/namex/package/solr_pkb.sql
- nro-legacy/sql/object/registry/namex/package/solr_pkb.sql
*Issue #, if available:* 959
*Description of changes:* Added code to escape quotation marks in names.
> Solr: add escaping of quotation marks. #959

- api/namex/models/nwpta.py
*Issue #, if available:* bcgov/name-examination#958
*Description of changes:* Added 'requested' flag to nwpta json.
> Added 'requested' flag to nwpta json.

- api/namex/services/nro/oracle_services.py
> Added logging to debug data issue in servers.

- api/Jenkinsfile
- api/Jenkinsfile_test
- api/config.py
- api/requirements/dev.txt
- api/requirements/prod.txt
- api/setup.py
- api/tests/postman/namex-pipeline-dev.postman_collection.json
- api/tests/postman/namex-pipeline-test.postman_collection.json
- colin-api/Jenkinsfile
- colin-api/pytest.ini
- colin-api/setup.py
- colin-api/tests/unit/conftest.py
- nro-extractor/Jenkinsfile
- solr/Jenkinsfile
*Issue #923:*
Solr, namex-api, colin-api, and nro-extractor pipelines deploy through to prod with informative slack msging
To do:
- pytests are not running properly yet
- webhooks need to be confirmed/added for each pipeline in github (I believe Thor + Richard are the only ones with permissions to do this)
> pipeline update for solr,namex-api,colin-api and nro extractor

- api/Jenkinsfile
added spacing to test if change will trigger the pipeline
> testing namex-api webhook

- api/Jenkinsfile
- nro-extractor/Jenkinsfile
- solr-admin-app/Jenkinsfile
- solr-feeder/Jenkinsfile
- solr-feeder/openshift/templates/pipeline-template.yaml
- solr/Jenkinsfile
*Issue #923:*
Solr-feeder-pipeline created + minor format changes
> solr-feeder-pipeline

- api/tests/postman/namex-pipeline-dev.postman_collection.json
- api/tests/postman/namex-pipeline-test.postman_collection.json
*Issue #928:*
Updated pipeline pm tests for uppercase backend change.
> pm test update

- solr/Jenkinsfile
*Issue #923:*
No changes bug fix (slack token added)
> solr-pipeline bug fix

- api/tests/postman/namex-pipeline-test.postman_collection.json
*Issue #928:*
pipeline tests updated for test env
> pm tests for TEST updated for backend change

- docs/cronjobs.md
*Issue #996:*
doc added for cron jobs
- includes basic info and oc commands
> cronjobs doc added

- api/Jenkinsfile
- colin-api/Jenkinsfile
- nro-extractor/Jenkinsfile
- solr-admin-app/Jenkinsfile
- solr-feeder/Jenkinsfile
- solr/Jenkinsfile
*Issue #923:*
Improved functionality to allow pipelines to be run even when there are no changes while also preventing it from running with no changes automatically.
> Pipelines update

- api/namex/analytics/restricted_words.py
- api/tests/postman/namex-pipeline-dev.postman_collection.json
- api/tests/postman/namex-pipeline-test.postman_collection.json
- api/tests/python/restricted_words/test_restricted_words.py
*Issue #1023:*
- updated to catch embedded words and strips special chars 
- Restricted words broken up into separate functions for pytests
- pm tests updated for better testing of restricted words
> restricted words bug-fix with pytests and pm tests

- nro-extractor/api/endpoints/requests.py
*Issue #, if available:* bcgov/name-examination#1013
Added corpnum to extractor - parse from Additional Info
> Added corpnum to extractor - parse from Additional Info

- nro-legacy/sql/object/names/namex/view/solr_dataimport_conflicts_vw.sql
- nro-legacy/sql/release/20181016_solr_view/names/namex/create.sql
*Issue #, if available:* 998
*Description of changes:* updated the namex view for conflicts with Lorna's changes.
> Solr: update names view. #998

- nro-extractor/Jenkinsfile
- nro-update/Jenkinsfile
Added myself to pipeline permissions (jenkins files) for updater and extractor pipelines.
> Added myself to pipeline permissions (jenkins files) for updater and extractor pipelines.

- api/namex/analytics/restricted_words.py
- api/tests/python/restricted_words/test_restricted_words.py
*Issue #, if available:1023*
- No longer returns embedded words
- pytests updated to reflect changes 
> restricted words update for embedded words

- api/Jenkinsfile
- api/tests/postman/namex-pipeline-dev.postman_collection.json
- api/tests/postman/namex-pipeline-test.postman_collection.json
- Put local pytests in a try/catch with slack notification
- updated pm tests for r-words to properly test new changes for embedded word rules
> slack msging for pass/fail on pytests + r-words pm update

- solr-synonyms-api/Jenkinsfile
- solr-synonyms-api/app.py
- solr-synonyms-api/config.py
- solr-synonyms-api/docs/readme.md
- solr-synonyms-api/openshift/solr-feeder-build.param
- solr-synonyms-api/openshift/solr-feeder-deploy.DEV.param
- solr-synonyms-api/openshift/solr-feeder-deploy.PROD.param
- solr-synonyms-api/openshift/solr-feeder-deploy.TEST.param
- solr-synonyms-api/openshift/templates/pipeline-template.yaml
- solr-synonyms-api/openshift/templates/solr-feeder-build.json
- solr-synonyms-api/openshift/templates/solr-feeder-deploy.json
- solr-synonyms-api/requirements.txt
- solr-synonyms-api/synonyms/__init__.py
- solr-synonyms-api/synonyms/endpoints/__init__.py
- solr-synonyms-api/synonyms/endpoints/probes.py
- solr-synonyms-api/synonyms/endpoints/synonyms.py
- solr-synonyms-api/synonyms/models/__init__.py
- solr-synonyms-api/synonyms/models/synonym.py
*Issue #, if available:* 1039
*Description of changes:* New ReST API - very simple, give it a term and it returns the synonyms list(s) containing the term, if any.
> Solr: API query with synonyms. #1039

- utils/convert-completed-nrs/.env
- utils/convert-completed-nrs/convert_completed_nrs.py
- utils/convert-completed-nrs/readme.md
*Issue #, if available:* bcgov/name-examination#1046
Added script to convert COMPLETED NRs based on name states - replicates extractor functionality; to be run once.
> Added script to convert COMPLETED NRs based on name states - replicates extractor functionality; to be run once.

- api/Jenkinsfile
- colin-api/Jenkinsfile
- jobs/Jenkinsfile
- nro-extractor/Jenkinsfile
- nro-update/Jenkinsfile
- solr-admin-app/Jenkinsfile
- solr-feeder/Jenkinsfile
- solr/Jenkinsfile
Permissions: katie + walter now have permissions to push all the pipelines through
Bug-fix: namex-api-pipeline was missing a bracket
Logic change: if/else reversed for condition on proceeding with build on 'no changes'
> pipeline updates (permissions/namex-api bug-fix/logic change)

- solr/trademarks/trademarks_loader.py
*Issue #, if available:* 1050
*Description of changes:* Changed the loader to do batches of 20 documents, and to only commit at the end. Also changed HTTP error reporting to be a little more robust.
> Solr: optimized the trademarks loader. #1050

- api/namex/resources/requests.py
*Issue #, if available:* bcgov/name-examination#1057
Added reporting stats for senior examiner review activities.
> Added reporting stats for senior examiner review activities.

- solr-synonyms-api/.s2i/environment
- solr-synonyms-api/gunicorn_config.py
- solr-synonyms-api/pytest.ini
- solr-synonyms-api/requirements.txt
- solr-synonyms-api/requirements/dev.txt
- solr-synonyms-api/requirements/prod.txt
- solr-synonyms-api/wsgi.py
*Issue #, if available:* 1039
*Description of changes:* Added Thor's gunicorn changes to the synonyms API.
> Switch to gunicorn server. #1039

- solr-synonyms-api/synonyms/__init__.py
*Issue #, if available:* 1039
*Description of changes:* Changed the SQLAlchemy initialization to hopefully fix a session problem.
> Updated SQLAlchemy initialization. #1039

- solr/docs/feeders.sql
- solr/docs/operations_manual.md
*Description of changes:* Added some extra items to the Solr operations manual. Added useful SQL queries for Oracle databases.
> Updated Solr documentation, added SQL scripts.

- nro-legacy/sql/object/names/namex/package/solr_pkb.sql
- nro-legacy/sql/object/registry/namex/package/solr_pkb.sql
- nro-legacy/sql/release/20181030_feeder_functions/names/namex/package_fix.sql
- nro-legacy/sql/release/20181030_feeder_functions/registry/namex/package_fix.sql
*Issue #, if available:* 1095
*Description of changes:* Added escaping of backslash characters so that they stop failing when submitting data to Solr.
> Fix bug for backslashes in names. #1095

- api/namex/resources/requests.py
- api/tests/postman/namex-pipeline-dev.postman_collection.json
- api/tests/postman/namex-pipeline-test.postman_collection.json
*Issue #1065:*
Added in new query filters and pm tests
> search update for new filters + pm tests

- api/tests/postman/namex-pipeline-test.postman_collection.json
*Issue #NA:*
Updated broken tests in pm test suite for TEST NS
> pm tests updated for search in test-ns

- api/config.py
- api/namex/models/event.py
- api/namex/services/audit_trail/event_recorder.py
- jobs/nro-update/config.py
- jobs/nro-update/nro_update.py
- jobs/nro-update/tests/conftest.py
- jobs/nro-update/tests/test_nro_datapump.py
- nro-extractor/config.py
*Issue #, if available:* bcgov/name-examination#1077
added event tracking to nro-update, 
updated the tests by adding setup for a Flask context
made the setup of the the service account the same across sub projects
> added event tracking to nro-update

- solr/requirements.txt
- solr/trademarks/trademarks_loader.py
- solr/trademarks/trademarks_parser.py
*Issue #, if available:* 1118
*Description of changes:* Added the registration number to the extracted trademarks data. This caused a rewrite of the parser to use a different XML parser, due to a bug. Also stopped exploding the ZIP files before parsing, the code now uses the in-ZIP files. Tweaked the loader to get around WIndows 10 problems.
> Added registration number to the trademarks parser. #1118

- nro-legacy/sql/object/names/namex/package/solr_pkb.sql
*Issue #, if available:* 1148
*Description of changes:* added the CANCL transaction to those that are removed from the possible.conflicts core.
> Updated Solr package to handle CANCL transactions. #1148

- api/namex/resources/requests.py
*Issue #, if available:* bcgov/name-examination#1163
check if state moves from anything other than INPROGRESS to INPROGRESS that the furnished flag is set to N.
> forced any transition into INPROGRESS to set the furnished flag to N

- api/namex/resources/requests.py
- api/tests/postman/namex-pipeline-dev.postman_collection.json
- api/tests/postman/namex-pipeline-test.postman_collection.json
*Issue #, if available:NA*
- updated pm tests for new data in prod (old test nr was wiped)
- updated pm tests for searching on 'completed' in state filter on search filter
- updated backend api for searching on 'completed' in state filter on search filter
> backend for filter state on completed on search page + pm test update

- api/namex/analytics/solr.py
- api/namex/resources/requests.py
- solr/cores/possible.conflicts/conf/managed-schema
*Issue #, N/A:*
Solr call added for the synonym bucket
> synonym bucket solr search added

- api/tests/postman/namex-pipeline-dev.postman_collection.json
- api/tests/postman/namex-pipeline-test.postman_collection.json
*Issue #, if available:NA*
Updated pipeline pm tests for dev + test to include priorityDate field
> pipeline pm tests updated to include priorityDate

- api/namex/resources/exact_match.py
- api/tests/python/end_points/test_exact_match.py
> lower case the query to work around boolean operators

- docs/database.md
- docs/developer.md
*Issue #, if available:* bcgov/entity#16
updated docs to fix typo and new branch naming
> updated docs to fix typo and new branch naming

- solr/cores_check.py
- solr/docs/solr_standalone_installation.md
- solr/requirements.txt
*Issue #, if available:* Solr - Syncing Solr daily and researching automation #2
*Description of changes:* Added script to compare Oracle and Solr cores.
> Added script to compare Oracle and Solr cores. #2

- solr/cores_check.py
*Issue #, if available:* #2
*Description of changes:* Added error handling to the Solr call, it now quits with an error message if the HTTP response is not 200.
> Added error handling to Solr/Oracle comparator. #2

- nro-legacy/requirements.txt
- nro-legacy/requirements/dev.txt
- nro-legacy/sql/object/registry/namex/view/office_vw.sql
- nro-legacy/sql/release/201811XX_namex/registry/namex/create.sql
- nro-legacy/tests/conftest.py
- nro-legacy/tests/postgres.py
- nro-legacy/tests/sql/create.table.office.sql
- nro-legacy/tests/test_office_vw.py
office_vw now only includes not null delivery_addr_id and null end_event_id
> fix issue #18

- api/namex/resources/requests.py
- api/tests/postman/namex-pipeline-dev.postman_collection.json
- api/tests/postman/namex-pipeline-test.postman_collection.json
*Issue #, if available:bcgov/entity#22*
- last update filter added
- pm tests updated
> last update filter added with tests

- .gitignore
- solr-admin-app/config.py
- solr-admin-app/requirements.txt
- solr-admin-app/requirements/dev.txt
- solr-admin-app/requirements/prod.txt
- solr-admin-app/tests/conftest.py
- solr-admin-app/tests/features/environment.py
- solr-admin-app/tests/features/hello.feature
- solr-admin-app/tests/features/steps/hello_steps.py
- solr-admin-app/tests/support/driver/ip_port_in_use.py
- solr-admin-app/tests/support/driver/server_driver.py
- solr-admin-app/tests/unit/test_tdd_ready.py
green test:
given we seed the database with one synonym
when we start the server, open firefox, access synonym list
then we see the synonym in the list
> tdd ready :)

- nro-legacy/sql/object/names/namex/view/nr_creation_date_vw.sql
- nro-legacy/sql/release/20181129_nr_creation_date_vw/names/namex/create.sql
*Issue #, if available:* 2
*Description of changes:* new view for troubleshooting syncing problems.
> Added new view for help syncing Oracle and postgres #2

- solr-admin-app/database/database_create.sql
- solr-admin-app/tests/conftest.py
- solr-admin-app/tests/features/environment.py
- solr-admin-app/tests/features/steps/synonyms_steps.py
- solr-admin-app/tests/features/synonym.list.feature
Document that the synonym list displays all the existing synonyms
> 24 - document synonym list

- solr-admin-app/tests/features/hello.feature
- solr-admin-app/tests/unit/test_tdd_ready.py
> Acknowledge the new welcome message

- solr-admin-app/database/database_create.sql
- solr-admin-app/requirements/dev.txt
- solr-admin-app/tests/conftest.py
- solr-admin-app/tests/features/environment.py
- solr-admin-app/tests/unit/test_restricted_conditions.py
- solr-admin-app/tests/unit/test_synonyms_list.py
- solr-admin-app/tests/unit/test_tdd_ready.py
> 24 - exploring restricted conditions

- api/namex/resources/requests.py
*Issue #, if available:bcgov/entity#22*
- update handles issue where timezone in openshift server is utc
> fixed timezone issue for lastModified filter

- api/namex/services/nro/change_nr.py
- api/tests/python/__init__.py
- api/tests/python/nro_services/test_update_request.py
- api/tests/python/util.py
we now preserve previous request id when updating request
> 20 - remove updates to nro request table

- solr/cores/possible.conflicts/conf/managed-schema
*Issue #, if available:bcgov/entity#12*
- added in lower case 's' removal in manage schema
> added in lower case s removal in txt_sarts_with

- nro-legacy/sql/object/names/namex/job/namex_outbound.sql
- nro-legacy/sql/object/names/namex/package/namex_pkb.sql
*Issue #, if available:* N/A
Fixed types/editor errors in package and job scripts
> fixed editor/typos

- jobs/nro-extractor/config.py
- jobs/nro-extractor/nro_extractor.py
- jobs/nro-extractor/openshift/templates/cron-nro-extractor.yml
Corrected missing edits from help PR
> corrected missing edits from prior commit

- api/namex/models/request.py
Removed priorityDate from request header schema to remove it from PUT.
> Removed priorityDate from request header schema to remove it from PUT save

- jobs/solr-synonym-updater/config.py
- jobs/solr-synonym-updater/multi_word_syns.txt
- jobs/solr-synonym-updater/openshift/scripts/Readme.md
- jobs/solr-synonym-updater/openshift/scripts/exportTemplate.sh
- jobs/solr-synonym-updater/openshift/scripts/jenkins-pvc.yaml
- jobs/solr-synonym-updater/openshift/templates/cron-solr-synonym-updater.yml
- jobs/solr-synonym-updater/openshift/templates/solr-synonym-updater-bc.json
- jobs/solr-synonym-updater/protected-multi.txt
- jobs/solr-synonym-updater/requirements.txt
- jobs/solr-synonym-updater/requirements/dev.txt
- jobs/solr-synonym-updater/requirements/prod.txt
- jobs/solr-synonym-updater/run.sh
- jobs/solr-synonym-updater/solr-synonym-updater.py
- data fix for multi synonyms
- will be using the 2 txt files it creates for solr changes
> Solr synonym updater

- api/namex/resources/requests.py
- api/tests/postman/namex-pipeline-dev.postman_collection.json
- api/tests/postman/namex-pipeline-test.postman_collection.json
*Issue #, if available:* bcgov/entity#32
Add auto-generated comment when name is changed. 
> Add generated comment when name changed.

- api/tests/postman/namex-pipeline-dev.postman_collection.json
- api/tests/postman/namex-pipeline-test.postman_collection.json
- test for comment add on name change was looking at the end of the comment array instead of the beginning - fixed
> fixed postman test error

- api/tests/python/end_points/test_synonym_match.py
- solr/cores/possible.conflicts/conf/managed-schema
bcgov/entity#60
- Put the money-handling filters into the text_en_splitting field in solr
- Add tests
- remove test for @kialj876 
- fix tests broken by double-letter
> Issue 60 sub money

- api/namex/analytics/solr.py
- api/tests/python/end_points/test_synonym_match.py
- solr/cores/possible.conflicts/conf/managed-schema
*Issue #, if available:bcgov/entity#78*
- old solr search for syn bucket added back in with the new solr search
> old syn bucket alg combined/tests updated

- api/namex/models/event.py
> add missing event state

- api/namex/services/nro/request_utils.py
- api/tests/python/nro_services/test_nro_request_utils.py
*Issue #, if available:* bcgov/entity/#59
Altered to allow all of the Jump settings to be added as Priority in NameX
> Altered priority to accept any of the Jump settings as a Priority

- nro-legacy/sql/object/registry/namex/view/solr_dataimport_conflicts_vw.sql
Removed order by clause and re-ran tests.
> removed order by clause for performance

- api/namex/resources/requests.py
- api/tests/postman/namex-pipeline-dev.postman_collection.json
- api/tests/postman/namex-pipeline-test.postman_collection.json
*Issue #, if available:* bcgov/entity#40
When status patched to draft in namex, set to D in NRO.
Also fixed bug in dev postman tests (wrong username) plus updated for latest changes.
> When status patched to draft in namex, set to D in NRO.

- api/tests/postman/namex-pipeline-dev.postman_collection.json
- api/tests/postman/namex-pipeline-test.postman_collection.json
> Added missing BDD call to TEST postman tests.

- api/namex/analytics/solr.py
- api/namex/resources/requests.py
- api/tests/python/__init__.py
- api/tests/python/end_points/test_cobrs_phonetic_match.py
- api/tests/python/end_points/test_sounds_like.py
- api/tests/python/end_points/test_synonym_match.py
- api/tests/python/util.py
*Issue #, if available:bcgov/entity#69 bcgov/entity#74*
- synonym conflict results ordered by synonyms
- synonym conflict results contain stem info
- stopwords stripped from search title and search
- tests added
> 68 alphabetize synonym results

- colin-api/app/resources/corporations.py
- colin-api/tests/unit/test_addr_id_sql.py
Added a test to all sql statements to prevent null address ids and supporting tests for for both xpro and bc corps.
> Colin change

- jobs/nro-update/nro/nro_datapump.py
- jobs/nro-update/nro_update.py
- jobs/nro-update/openshift/templates/cron-nro-update.yml
- jobs/nro-update/requirements/prod.txt
- jobs/nro-update/tests/test_nro_datapump.py
- jobs/nro-update/util/job_tracker.py
> 81 nro update jaeger

- api/namex/services/nro/oracle_services.py
I had approved a change but the error was bumped into a nested code block, and should not have been. Also cleaned up some comments.
> reverted error handling to previous version, due to error approved

- api/namex/resources/requests.py
- api/tests/postman/namex-pipeline-dev.postman_collection.json
- api/tests/postman/namex-pipeline-test.postman_collection.json
*Issue #, if available:bcgov/entity#126*
- added validation on editing name choices
- updated pm tests
- include a test suite for editing name choices
- also will no longer fail on the nro_change error (still makes sure that it's that specific error and that namex is properly updated)
> edit name choice validation and pm test updates

- api/tests/postman/namex-pipeline-dev.postman_collection.json
- api/tests/postman/namex-pipeline-test.postman_collection.json
Signed-off-by: Kial Jinnah <kial.jinnah@gov.bc.ca>
*Issue #, if available:bcgov/entity#126*
- fixed syntax error in pm test
> fixed pm test syntax error

- api/namex/analytics/solr.py
- api/tests/python/end_points/test_synonym_match.py
*Issue #, if available:bcgov/entity#222*
- fixed missed results bug
- added pytest to secure it
> missed results bug fix

- namex-db/Jenkinsfile
- namex-db/Jenkinsfile.pipeline.param
- namex-db/PortForwardingaDatabase.md
- namex-db/README.md
- namex-db/config/postgresql-cfg/autovacuum.conf
- namex-db/openshift/.gitignore
- namex-db/openshift/postgresql-build.namex.param
- namex-db/openshift/postgresql-build.param
- namex-db/openshift/postgresql-deploy.dev.param
- namex-db/openshift/postgresql-deploy.namex.dev.param
- namex-db/openshift/postgresql-deploy.namex.param
- namex-db/openshift/postgresql-deploy.namex.prod.param
- namex-db/openshift/postgresql-deploy.namex.test.param
- namex-db/openshift/postgresql-deploy.overrides.sh
- namex-db/openshift/postgresql-deploy.param
- namex-db/openshift/postgresql-deploy.prod.param
- namex-db/openshift/postgresql-deploy.test.param
- namex-db/openshift/templates/postgresql-build.json
- namex-db/openshift/templates/postgresql-deploy.json
> add db upgrade

- api/tests/postman/namex-pipeline-dev.postman_collection.json
- api/tests/postman/namex-pipeline-test.postman_collection.json
removed consumptionDate from postman tests, to match code change
> removed consumptionDate from postman tests, to match code change

- api/tests/python/end_points/test_requests.py
Fixed failing pytest.
Was probably passing before due to fluke data? Unclear but definitely
wasn't working as expected now.
> Fixed failing pytest

- jobs/nro-extractor/Jenkinsfile
*Issue #, if available:bcgov/entity#320*
- pipeline fix for extractor (hasn't been updated since new code)
> pipeline update for extractor

- api/namex/services/nro/oracle_services.py
- jobs/nro-extractor/extractor/app.py
> Added more logging for extractor

- api/namex/analytics/solr.py
- api/namex/resources/requests.py
- api/tests/postman/namex-pipeline-dev.postman_collection.json
- api/tests/postman/namex-pipeline-test.postman_collection.json
- api/tests/python/end_points/test_cobrs_phonetic_match.py
- api/tests/python/end_points/test_sounds_like.py
- api/tests/python/end_points/test_synonym_match.py
*Issue #, if available:bcgov/entity#203*
- bug fixed: confirmed with kaine on how it is handled
- pytests added
- pm tests added
> bug fixed with tests

- api/namex/analytics/solr.py
- api/namex/resources/requests.py
- api/namex/services/nro/oracle_services.py
- api/tests/postman/namex-pipeline-dev.postman_collection.json
- api/tests/postman/namex-pipeline-test.postman_collection.json
- api/tests/python/end_points/test_cobrs_phonetic_match.py
- api/tests/python/end_points/test_requests.py
- api/tests/python/end_points/test_sounds_like.py
- api/tests/python/end_points/test_synonym_match.py
- jobs/nro-extractor/Jenkinsfile
- jobs/nro-extractor/extractor/app.py
- cherrypicked from master to exclude needed oracle changes
> Cherrypickedmaster

- api/tests/python/nro_services/test_update_request.py
> Removed destructive test - could drop request table from NRO.

- docs/database_refresh.md
*Issue #, if available:* 355
*Description of changes:* documentation on the reload process for NAMESD. Probably still some data syncing needed to clean up weirdnesses but it could just be old and crufty data.
> Documentation on the NAMESD reload. #355

- api/Jenkinsfile
- colin-api/Jenkinsfile
- jobs/inprogress_update/Jenkinsfile
- jobs/nro-extractor/Jenkinsfile
- jobs/nro-update/Jenkinsfile
- solr-admin-app/Jenkinsfile
- solr-feeder/Jenkinsfile
- solr/Jenkinsfile
> changed -edit to -admin user

- nro-legacy/sql/object/registry/namex/view/solr_conflicts_core_vw.sql
- nro-legacy/sql/release/20190425_solr_view/registry/namex/create.sql
*Issue #, if available:* 338
*Description of changes:* New view for delta loading corporations into the possible.conflicts view.
> Added view for conflicts core delta updates. (#338)

- solr/database/solr_names_core_vw.sql
*Issue #, if available:* 346
*Description of changes:* Added a new PostgreSQL view for doing delta imports into the names core.
> Added view for names core delta updates (#346)

- jobs/nro-extractor/extractor/app.py
> extractor - do not ignore consumed transactions

- api/namex/resources/requests.py
- api/tests/postman/namex-pipeline-dev.postman_collection.json
- api/tests/postman/namex-pipeline-test.postman_collection.json
- api/tests/python/end_points/test_requests.py
*Issue #, https://github.com/bcgov/entity/issues/525
> Add Comment Enhancements

- api/namex/models/name.py
- api/tests/postman/namex-pipeline-dev.postman_collection.json
- api/tests/postman/namex-pipeline-test.postman_collection.json
https://github.com/bcgov/entity/issues/629
Add consumption_date and corp_num to as_dict in the name model.
Add a consumed test for dev and test in postman.
> Updates for ConsumptionDate and CorpNum for Consumed NR

- nro-legacy/sql/object/names/namex/package/solr_pkb.sql
- nro-legacy/sql/object/names/namex/view/solr_dataimport_conflicts_vw.sql
- nro-legacy/sql/object/names/namex/view/solr_dataimport_names_vw.sql
- nro-legacy/sql/object/registry/namex/package/solr_pkb.sql
- nro-legacy/sql/object/registry/namex/view/solr_dataimport_conflicts_vw.sql
- nro-legacy/sql/release/201907XX_solr_oracle/names/namex/create.sql
- nro-legacy/sql/release/201907XX_solr_oracle/registry/namex/create.sql
- solr/cores/names/conf/managed-schema
- solr/cores/possible.conflicts/conf/managed-schema
Signed-off-by: Lorna Trent <lorna.trent@gov.bc.ca>
These changes are required to through to production before the solr.py script can be updated to include two new fields in the conflict list and name history list.  The fields are start date and jurisdiction for both cores, names and possible conflicts.
> solr oracles changes for 689

- api/tests/postman/namex-pipeline-test.postman_collection.json
Signed-off-by: Lorna Trent <lorna.trent@gov.bc.ca>
Error found in data in the Check Consumed test in the Test environment.  Corrected expected consumed date and corp_num. 
> correction to check consumed name postman test for test

- api/migrations/versions/0c6b29c57638_.py
- api/namex/models/event.py
> 993 event table correction

- api/namex/models/event.py
- api/namex/services/audit_trail/event_recorder.py
- api/tests/python/end_points/test_requests.py
https://github.com/bcgov/entity/issues/1014
Updated event recorder, event model and  py test to verify use of the new jsonb column in the event. The column was already deployed to all environments in a previous PR. After this I will do the datafix.
> 1014 event recorder

- jobs/event-json-datafix/config.py
- jobs/event-json-datafix/event-json-datafix.py
- jobs/event-json-datafix/openshift/scripts/Readme.md
- jobs/event-json-datafix/openshift/scripts/exportTemplate.sh
- jobs/event-json-datafix/openshift/scripts/jenkins-pvc.yaml
- jobs/event-json-datafix/openshift/templates/cron-event-json-datafix.yml
- jobs/event-json-datafix/openshift/templates/event-json-datafix.json
- jobs/event-json-datafix/requirements.txt
- jobs/event-json-datafix/requirements/dev.txt
- jobs/event-json-datafix/requirements/prod.txt
- jobs/event-json-datafix/run.sh
To take the contents of the json_zip column, decompress it and store the json in the new jsonb column.
> 994 event datafix job

- api/namex/analytics/solr.py
- api/requirements/prod.txt
Added missing fields to phonetics bucket, start_date, jurisdiction. Tests already in place.
Corrected duplicate packages in requirements.txt from a previous PR.
> 1118 solr query fl

- jobs/notebook-report/notebookreport.py
- jobs/notebook-report/openshift/templates/cron-notebook-report.yml
- jobs/notebook-report/tests/unit/test_job.py
Signed-off-by: IDIR\schen <steven.chen@gov.bc.ca>
> 600-Generate Jupyter Notebook Reports for Namex

- COMPLIANCE.yaml
Updated status of PIA and STRA
> compliance-state

- api/namex/services/name_processing/name_processing.py
- api/namex/services/synonyms/synonym.py
- api/tests/python/namex_services/synonyms/__init__.py
- api/tests/python/namex_services/synonyms/test_synonym.py
> 3055 regex transform

- api/namex/models/request.py
> corrected listener

- api/namex/models/request.py
- api/namex/services/name_request/auto_analyse/__init__.py
- api/namex/services/name_request/auto_analyse/name_analysis_utils.py
- api/namex/services/name_request/auto_analyse/protected_name_analysis.py
- api/namex/services/name_request/name_analysis_builder_v2/name_analysis_builder.py
- api/namex/services/synonyms/mixins/designation.py
- api/namex/services/synonyms/synonym.py
*Correct Conflict Issues #3127*
* Remove prefix Regular Expression rule
* Move creation of possible combinations to check_name_is_well_formed. If there is no valid combination, then we do not proceed with search_conflicts execution.
* Get substitutions in ordered dictionary to compare by index each word. Extended the score for assessing each word.
* Lessen query in search for distinctive word
* Increase the threshold for conflict matching to greater than 0.68 similarity index
> 3127 correct conflict issues

- solr-synonyms-api/requirements/prod.txt
> added missing req

- api/Jenkinsfile
- api/requirements/prod.txt
> Fix reqs and creds

- api/Jenkinsfile
> updated setup tools for nltk

- solr-synonyms-api/requirements/prod.txt
> add missing package

- api/namex/services/name_request/auto_analyse/protected_name_analysis.py
- api/namex/services/name_request/name_analysis_builder_v2/name_analysis_builder.py
- solr-synonyms-api/synonyms/endpoints/synonyms.py
- solr-synonyms-api/synonyms/services/synonyms/mixins/designation.py
- solr-synonyms-api/synonyms/services/synonyms/synonym.py
*#3317: Refine Conflict Matching*
* Fixes related to designations
* Refine conflict matching
> 3317 refine conflict matching

- api/namex/resources/auto_analyse/analysis_issues.py
- api/namex/resources/auto_analyse/analysis_response.py
- api/namex/services/name_request/auto_analyse/name_analysis_director.py
- api/namex/services/name_request/auto_analyse/protected_name_analysis.py
*Issue 3168, Check Special Restricted Words*
Add Checking for special restricted words after unclassified and before consents
Add same checkbox as unclassified.
> 3168 check special restricted words

- api/namex/resources/auto_analyse/analysis_issues.py
- api/namex/resources/auto_analyse/analysis_options.py
- api/namex/resources/auto_analyse/analysis_response.py
- api/namex/services/name_request/auto_analyse/__init__.py
- api/namex/services/name_request/auto_analyse/abstract_name_analysis_builder.py
- api/namex/services/name_request/auto_analyse/name_analysis_director.py
- api/namex/services/name_request/auto_analyse/protected_name_analysis.py
- api/namex/services/name_request/name_analysis_builder_v2/name_analysis_builder.py
#3097, Check for No Designation:*
Add new check/response for designation existence
New add_designation_setup()
> 3097 check for no designation

- api/namex/models/name.py
- api/namex/resources/requests.py
- api/tests/python/end_points/test_requests.py
> 3295 clean name

- api/namex/resources/auto_analyse/analysis_issues.py
- api/namex/resources/auto_analyse/analysis_options.py
- api/namex/services/name_processing/name_processing.py
- api/namex/services/name_request/auto_analyse/abstract_name_analysis_builder.py
- api/namex/services/name_request/auto_analyse/mixins/get_designations_lists.py
- api/namex/services/name_request/auto_analyse/name_analysis_director.py
- api/namex/services/name_request/auto_analyse/name_analysis_utils.py
- api/namex/services/name_request/auto_analyse/protected_name_analysis.py
- api/namex/services/name_request/name_analysis_builder_v2/name_analysis_builder.py
- api/namex/utils/common.py
- solr-synonyms-api/synonyms/services/synonyms/synonym.py
*3246 #,Designations Enters Without the Periods Cause Bad Behaviour:*
This PR doe not contain any work related to well_formed and includes the following changes:
-Fixes for upper case
-Fix in add_descriptive_setup function
-Fix for designations with no dot
-Fixes related to remove french
-Fixes to set together two letters such as B,S&J ENTERPRISES LTD.
> 3246 no wellformed designations enters without periods

- api/namex/resources/auto_analyse/analysis_issues.py
- api/namex/resources/auto_analyse/analysis_response.py
- api/namex/resources/auto_analyse/response_objects/name_action.py
- api/namex/services/name_processing/mixins/get_synonym_lists.py
- api/namex/services/name_processing/name_processing.py
- api/namex/services/name_request/auto_analyse/name_analysis_utils.py
- api/namex/services/name_request/name_analysis_builder_v2/name_analysis_builder.py
- solr-synonyms-api/synonyms/endpoints/synonyms.py
*#3545, Regex Picking C in BC numbered companies:*
-Fix in searching for mismatches in designation comparison with name
> 3545 regex picking c in bc numbered companies

- api/namex/resources/auto_analyse/analysis_issues.py
- api/namex/services/name_request/auto_analyse/abstract_name_analysis_builder.py
- api/namex/services/name_request/auto_analyse/mixins/get_designations_lists.py
- api/namex/services/name_request/auto_analyse/protected_name_analysis.py
- api/namex/services/name_request/name_analysis_builder_v2/name_analysis_builder.py
> Areyeslo 3476 handle missing period on designation

- api/namex/services/nro/change_nr.py
> fixed failing inserts due to oracle env changes

- jobs/clean-name-datafix/openshift/templates/clean-name-datafix-bc.json
- jobs/clean-name-datafix/openshift/templates/clean-name-datafix.yml
> 3640 clean name job

- jobs/clean-name-datafix/run.sh
> Update filename in run.sh.

- jobs/clean-name-datafix/openshift/templates/clean-name-datafix.yml
> fixed parm for db name

- jobs/clean-name-datafix/openshift/templates/clean-name-datafix.yml
> updated parm

- jobs/clean-name-datafix/openshift/templates/clean-name-datafix.yml
> corrected parm

- jobs/clean-name-datafix/config.py
- jobs/clean-name-datafix/openshift/templates/clean-name-datafix.yml
> added missing env

- jobs/clean-name-datafix/clean-name-datafix.py
> updated max rows

- api/namex/constants/__init__.py
- api/namex/models/request.py
- api/namex/resources/requests.py
> chnages for consent_flag, date and BC request type

- solr-admin-app/solr_admin/__init__.py
- solr-admin-app/solr_admin/models/word_classification.py
- solr-admin-app/solr_admin/views/synonym_view.py
- solr-admin-app/solr_admin/views/word_classification_view.py
> 2995 admin app

- solr-admin-app/solr_admin/models/word_classification.py
> corrected column name

- api/namex/resources/requests.py
> missed adding the consent fields upon edit

- api/namex/resources/name_requests.py
> fixes for post route and method

- api/namex/resources/name_requests.py
> added some error trapping removed model expect

- api/namex/resources/name_requests.py
> added logging and response for errors

- api/namex/resources/name_requests.py
> added more logging and error trapping in names section

- api/namex/resources/name_requests.py
> added consent checking for none

- api/namex/resources/name_requests.py
> fix consent word empty or none

- api/namex/resources/name_requests.py
> empty consent list

- api/namex/resources/name_requests.py
> consent list issue

- api/namex/resources/name_requests.py
> consent list logging

- api/namex/resources/name_requests.py
- api/namex/services/nro/change_nr.py
> environment flags

- api/namex/resources/requests.py
> added error tracing

- api/namex/resources/requests.py
removed name cleaning service as error trapping didnt give the reason for the 500.
> removed name cleaning

- api/namex/models/request.py
- api/namex/resources/auto_analyse/analysis_issues.py
- api/namex/resources/auto_analyse/response_objects/conflict.py
- api/namex/services/name_request/name_analysis_builder_v2/name_analysis_builder.py
- api/tests/python/end_points/auto_analyse/protected_names/test_auto_analyse_invalid_np_bc.py
*#3693, Update Search Conflict Query:*
1.  Update search conflict query to include consumed and not consumed names:
- Consumed Names: Checking corp_num is not NULL.
- Not Consumed Names: Checking expiration date greater than current date and corp_num is NULL and consumption_date is NULL.
2.  Add corp_num and consumption_date to search-conflicts response.
3. Add checks for existence of new parameters in test cases for search_conflicts.
> 3693 update search conflict query

- api/namex/resources/name_requests.py
- api/namex/services/nro/add_nr.py
- api/namex/services/nro/oracle_services.py
> 3406 add nr

- api/namex/models/request.py
- api/namex/resources/events.py
- api/namex/resources/name_requests.py
- api/namex/resources/requests.py
> odds and ends clean-up

- api/namex/resources/requests.py
- api/namex/services/nro/change_nr.py
- api/tests/python/end_points/test_events.py
- api/tests/python/end_points/test_requests.py
> 3730 consent received

- api/namex/services/name_processing/name_processing.py
- api/namex/services/name_request/auto_analyse/name_analysis_director.py
- api/namex/services/name_request/auto_analyse/name_analysis_utils.py
- api/namex/services/name_request/builders/name_analysis_builder.py
- api/tests/python/end_points/auto_analyse/common.py
- api/tests/python/end_points/auto_analyse/protected_names/test_add_distinctive_word_base_request.py
- solr-synonyms-api/synonyms/endpoints/synonyms.py
- solr-synonyms-api/synonyms/services/synonyms/mixins/model.py
- solr-synonyms-api/synonyms/services/synonyms/synonym.py
*#3831, Update Well Formed Name:*
Classify as descriptive if the first word is in the synonym table.
- Classify as descriptive words when they are found in synonym table under the same category. For instance, COFFEE SHOP if coffee and shop are in the same category.
- Fix for company word included as stop word. Designations were affected such as ['community contribution company', 'unlimited liability company', 'limited liability company', 'limited liability co.', 'co-operative', 'co-op']
- Added more scenarios in test_add_distinctive_word_base_request.
> 3831 v2 update well formed name

- nro-legacy/sql/object/registry/namex/view/conflicts_with_no_nrs_vw.sql
- nro-legacy/sql/release/20200603_conflicts_with_no_nrs_view/registry/namex/create.sql
> oracle view creation scripts for conflicts with no nrs

- api/namex/constants/__init__.py
- api/namex/models/request.py
- api/namex/resources/auto_analyse/issues/corporate_name_conflict.py
- api/namex/resources/auto_analyse/response_objects/conflict.py
- api/namex/services/name_request/auto_analyse/abstract_name_analysis_builder.py
- api/namex/services/name_request/builders/name_analysis_builder.py
- api/tests/python/end_points/auto_analyse/common.py
- api/tests/python/end_points/auto_analyse/protected_names/test_corporate_name_conflict_request.py
- solr-synonyms-api/synonyms/constants/__init__.py
- solr-synonyms-api/synonyms/services/synonyms/mixins/designation.py
*#3841, Add corp num to conflict issue:*
- Adding the following new fields to the response in CORPORATE_CONFLICT issue:
start_Date: consumption_date if consumed otherwise submission_date
id: corp_num if consumed otherwise nrNum
source: corp  if consumed otherwise nr
- Refactor search conflict methods to hold all fields needed in just list_details variable.
> 3841 add corp num conflict issue

- api/namex/services/name_request/auto_analyse/abstract_name_analysis_builder.py
- api/namex/services/name_request/auto_analyse/mixins/get_word_classification_lists.py
- api/namex/services/name_request/auto_analyse/name_analysis_director.py
- api/namex/services/name_request/auto_analyse/name_analysis_utils.py
- api/namex/services/name_request/builders/name_analysis_builder.py
- api/tests/python/end_points/auto_analyse/protected_names/test_add_descriptive_word_both_classifications_request.py
- api/tests/python/end_points/auto_analyse/protected_names/test_add_distinctive_word_base_request.py
- api/tests/python/end_points/auto_analyse/protected_names/test_corporate_name_conflict_request.py
- api/tests/python/end_points/auto_analyse/protected_names/test_corporate_name_conflict_strip_out_numbers_request.py
- api/tests/python/end_points/auto_analyse/protected_names/test_name_requires_consent_compound_word_request.py
- solr-synonyms-api/requirements/prod.txt
- solr-synonyms-api/synonyms/services/synonyms/__init__.py
- solr-synonyms-api/synonyms/services/synonyms/synonym.py
*#3919, Update Well Formed Name:*
- Check if each word is in synonyms table excluding Stops and Subs. If the word exists then it is added to descriptive and deleted from distinctive. 
- It is not longer considered the category in synonyms table
- Well formed handle the pattern DIST-DESC-DIST
- Updated test cases
Update in synonym table for stand-alone required.
> 3919 update well formed name

- nro-legacy/sql/object/registry/namex/view/conflicts_with_no_nrs_vw.sql
> added vw to view name

- nro-legacy/sql/object/names/namex/package/namex_pkb.sql
- nro-legacy/sql/release/202006XX_namex/names/namex/create.sql
> 3719 namex feeder

- api/namex/constants/__init__.py
> corrected for source event listener

- api/namex/models/name.py
- api/namex/resources/events.py
> added back name state for oracle get next

- nro-legacy/sql/object/names/namex/procedure/sync_consumed_names.sql
- nro-legacy/sql/release/202006XX_namex-proc/names/namex/create.sql
> prco used to sync data between colin,names, namex

- api/namex/constants/__init__.py
> updated request type mapping with benefit request types

- api/namex/utils/common.py
- api/requirements/prod.txt
(cherry picked from commit 2c802b9cba095a5ee8056b3280818ff2f7baca17)
*#4031, Reduce  Package Overhead:*
Replace pattern for inflect library for Python 3.6
> 4030-ReducePackageOverhead

- nro-legacy/sql/object/registry/namex/view/conflicts_with_no_nrs_vw.sql
- nro-legacy/sql/release/20200708_conflicts_with_no_nrs_view/registry/namex/create.sql
> updated view for bc numbered companies only

- api/namex/models/word_classification.py
- api/namex/resources/__init__.py
- api/namex/resources/events.py
- api/namex/resources/word_classification/__init__.py
- api/namex/resources/word_classification/word_classification.py
- api/namex/services/word_classification/word_classification.py
> 3803-Classify-Words-Updates

- api/namex/resources/word_classification/word_classification.py
> fix wordrequest payload order

- api/namex/resources/name_requests/base_name_request.py
- api/namex/resources/name_requests/name_requests.py
- api/namex/services/nro/add_nr.py
Removed NRO updated from the POST for DRAFT and added it to the PUT so that it is after payment in the workflow.
Added a conversion of priority cd in add_nr for Oracle priroity codes in request instance create.
Changed the order of solr add and delet in the PUT.  We must have the new doc in before deleting the old doc.
Fixed solr delete and removed sorl query as we dont need it.
> 4312 part b

- api/namex/services/name_request/builders/name_analysis_builder.py
*3840 #, Fix for Not Finding Conflicts:*
Needed to round similarity to two decimal digits for comparison.
> Fix in rounding similarity to two decimal digits.

- api/namex/resources/requests.py
- api/tests/python/end_points/test_requests.py
> removed clean-name from name approval in namex

- api/namex/models/name.py
> fixed name schema for namex

- api/namex/resources/auto_analyse/issues/corporate_name_conflict.py
> removed pytest imports

- api/namex/services/nro/change_nr.py
> corrected consent flag bug

- api/namex/resources/name_requests/resource.py
- api/namex/services/name_request/name_request.py
> Request actions v3

- api/namex/resources/name_requests/name_request.py
> 1 year and 56 days for REH and REN

- api/namex/services/name_request/name_request.py
> english and person flag did not handle none

- api/namex/constants/__init__.py
- api/namex/resources/auto_analyse/paths/bc_name_analysis/bc_name_analysis.py
- api/namex/resources/auto_analyse/paths/xpro_name_analysis/xpro_name_analysis.py
- api/namex/services/name_request/auto_analyse/__init__.py
> locked down back-end request action for xpro and fixed MVE

- api/namex/resources/name_requests/name_requests.py
- api/namex/resources/name_requests/resource.py
> only corps can be included in solr as conflicts

- api/namex/models/request.py
> added payment relationship

- api/namex/resources/name_requests/configuration.py
- jobs/nro-extractor/config.py
to get the extractor working with the updated namex api
> Extractor fixes

- api/namex/services/name_request/auto_analyse/name_analysis_director.py
- api/namex/services/name_request/auto_analyse/name_analysis_utils.py
- api/namex/services/name_request/builders/name_analysis_builder.py
- api/tests/python/end_points/auto_analyse/protected_names/test_corporate_name_conflict_compound_descriptive_request.py
- api/tests/python/end_points/auto_analyse/protected_names/test_corporate_name_conflict_compound_distinctive_request.py
- api/tests/python/end_points/auto_analyse/protected_names/test_corporate_name_conflict_request.py
- api/tests/python/end_points/auto_analyse/protected_names/test_corporate_name_conflict_strip_out_numbers_request.py
- solr-synonyms-api/synonyms/services/synonyms/synonym.py
*#4805, Add Compound Descriptives:*
- Identify  in the provided name valid synonyms including compound descriptives made of two or more words such as dry cleaner, car wash, bio fuel, etc.
- Generate possible distinctive compound words to search for conflicts.
> 4805 add compound descriptives v2

- api/namex/services/nro/request_utils.py
source must be referenced by the column name in model rather than the property name for the extractor.
> fix soure ref error for extractor

- api/namex/constants/__init__.py
- api/namex/resources/auto_analyse/paths/xpro_name_analysis/xpro_name_analysis.py
> 4971 fix xpro aml

- api/namex/services/nro/change_nr.py
> Consent fix

- api/namex/resources/name_requests/resource.py
Fixes issue with feature flag built-in functin not working to restrict posts in prod.
> fixed feature flag to restrict db saves

- api/namex/models/word_classification.py
- api/tests/python/end_points/auto_analyse/protected_names/test_add_descriptive_word_both_classifications_request.py
*4972#, Check Original Words In Word Classification:*
Retrieve from word_classification table words with added apostrophe and letter such as ACKMED'S
> 4972/Check Original Words In Word Classification

- api/namex/constants/__init__.py
- api/namex/resources/name_requests/resource.py
> corrections for oracle v2 for 5008

- api/namex/resources/name_requests/resource.py
- api/namex/services/nro/add_nr.py
- api/namex/services/nro/change_nr.py
> fixed oracle issues for the patch

- api/namex/services/name_request/name_request.py
> add missing fields for db save

- api/namex/resources/name_requests/base_nr_resource.py
- api/namex/resources/name_requests/constants.py
- api/namex/resources/name_requests/name_request.py
- api/namex/resources/name_requests/name_requests.py
> Hotfix/fix request+contact edit states

- api/namex/services/name_request/auto_analyse/xpro_name_analysis.py
*5190 #, XPRO AUTO-ANALYZE - Needs to be the same as BC Protected :*
XPRO Auto analyze executes the same search query than BC Protected when the name includes all words in the same category. In that, scenario search conflicts will exhaust all possible combinations of distinctive and descriptive in the name.
No changes required in BC Protected.
> Add check for search conflicts when name is not well formed in XPRO.

- api/namex/constants/__init__.py
- api/namex/services/name_request/auto_analyse/name_analysis_utils.py
- api/namex/services/name_request/builders/name_analysis_builder.py
- solr-synonyms-api/synonyms/constants/__init__.py
*5194 #, AUTO-ANALYZE- A few issues*
Fixes in SOCIETY abbreviation defined in init file
Fix in removing descriptives in same category when duplicates anywhere
Send correct descriptive list when getting vector 2.
> 5194 auto analyze few issues

- services/auto-analyze/.devcontainer/Dockerfile
- services/auto-analyze/.devcontainer/devcontainer.json
- services/auto-analyze/Dockerfile
- services/auto-analyze/LICENSE
- services/auto-analyze/Makefile
- services/auto-analyze/README.md
- services/auto-analyze/requirements.txt
- services/auto-analyze/requirements/dev.txt
- services/auto-analyze/requirements/prod.txt
- services/auto-analyze/setup.cfg
- services/auto-analyze/setup.py
- services/auto-analyze/src/auto_analyze/__init__.py
- services/auto-analyze/src/auto_analyze/analyzer.py
- services/auto-analyze/src/auto_analyze/version.py
- services/auto-analyze/tests/__init__.py
- services/auto-analyze/tests/conftest.py
- services/auto-analyze/tests/unit/__init__.py
- services/auto-analyze/tests/unit/test_analyzer.py
- services/auto-analyze/tests/unit/test_auto_analyzer_api.py
- services/auto-analyze/wsgi.py
- initial shell for the auto-analyzer service
> initial shell for auto-analyzer service

- jobs/auto-analyser-uat/Dockerfile
> added dockerfile

- jobs/auto-analyser-uat/Dockerfile
- jobs/auto-analyser-uat/run.sh
> fixed docker/run file

- .github/workflows/auto-analyze-cd.yml
- .github/workflows/auto-analyze-ci.yml
- services/auto-analyze/Jenkinsfiles/deploy-prod.groovy
- services/auto-analyze/k8s/README.md
- services/auto-analyze/k8s/deploy.dev.template.param
- services/auto-analyze/k8s/templates/deploy.json
> Added CI/CD flows and openshift templates.

- jobs/auto-analyser-uat/openshift/cronjob.param
- jobs/auto-analyser-uat/openshift/job.param
- jobs/auto-analyser-uat/openshift/templates/cronjob.json
- jobs/auto-analyser-uat/openshift/templates/job.json
- jobs/auto-analyser-uat/run.sh
> deployment fixes

- jobs/auto-analyser-uat/run.sh
> fix db upgrade

- jobs/auto-analyser-uat/auto_analyser_uat.py
- jobs/auto-analyser-uat/openshift/job.param
- jobs/auto-analyser-uat/openshift/templates/cronjob.json
- jobs/auto-analyser-uat/openshift/templates/job.json
> final fixes?

- jobs/auto-analyser-uat/auto_analyser_uat.py
> fixed update job

- jobs/auto-analyser-uat/auto_analyser_uat.py
- fixes current issue in prod for uat_rejection test being stuck
> added sqlalchemy text wrap to cover multiple edge cases

- jobs/auto-analyser-uat/auto_analyser_uat.py
- jobs/auto-analyser-uat/setup.py
> 5094 auto analyzer uat

- services/auto-analyze/wsgi.py
> added back

- services/auto-analyze/Dockerfile
- services/auto-analyze/auto_analyze/analyzer.py
> Docker version

- api/Makefile
- api/config.py
- api/namex/__init__.py
- api/setup.cfg
*Issue #5005:*
- see ticket for details
- cleaned up linters in configs I needed to touch
> sentry intitialization for namex-api

- api/requirements/prod.txt
- api/setup.cfg
> 5005 sentry for namex

- jobs/auto-analyser-uat/run_auto_analyser_uat.py
- jobs/auto-analyser-uat/src/auto_analyser_uat/models/request_name.py
> accuracy enhancement and bug fix

- api/namex/models/event.py
- api/namex/models/virtual_word_condition.py
- api/namex/resources/name_requests/base_nr_resource.py
- api/namex/resources/name_requests/name_request.py
- api/namex/resources/payment/payment.py
- api/namex/services/name_request/name_request.py
- api/namex/services/statistics/wait_time_statistics.py
> 5019 fix put for stats

- jobs/auto-analyser-uat/run_auto_analyser_uat.py
> query bug fix

- jobs/inprogress_update/requirements/prod.txt
- jobs/notebook-report/requirements/prod.txt
- jobs/nr-garbage-collector/requirements/prod.txt
- jobs/nro-extractor/requirements/prod.txt
- jobs/nro-get-decision-data/requirements/prod.txt
- jobs/nro-update/requirements/prod.txt
- jobs/rejection-uat/requirements/prod.txt
- jobs/solr-synonym-updater/requirements/prod.txt
- services/auto-analyze/requirements.txt
- services/auto-analyze/requirements/prod.txt
- added sentry sdk to everything that imports namex
> added sentry_sdk to reqs

- services/auto-analyze/requirements.txt
- services/auto-analyze/requirements/prod.txt
> trying req fix

- api/config.py
- api/namex/__init__.py
- api/requirements/prod.txt
- jobs/inprogress_update/requirements/prod.txt
- jobs/notebook-report/requirements/prod.txt
- jobs/nr-garbage-collector/requirements/prod.txt
- jobs/nro-extractor/requirements/prod.txt
- jobs/nro-get-decision-data/requirements/prod.txt
- jobs/nro-update/requirements/prod.txt
- jobs/rejection-uat/requirements/prod.txt
- jobs/solr-synonym-updater/requirements/prod.txt
- services/auto-analyze/requirements.txt
- services/auto-analyze/requirements/prod.txt
> taking sentry out

- api/namex/resources/auto_analyse/issues/corporate_name_conflict.py
> updated text and return values for queue conflict response

- services/auto-analyze/auto_analyze/analyzer.py
*5271 #, Update Weighting of Dist and Desc for Scoring Conflicts:*
- Modified scores for distinctive and descriptive. Distinctive differences are not as costly as descriptive differences.
> Updating weight for distinctive

- jobs/nr-garbage-collector/nr_garbage_collector.py
> fix due to namex-api change

- api/namex/resources/payment/payment.py
- api/namex/services/name_request/name_request.py
> 4939 fix expiry

- jobs/nr-garbage-collector/nr_garbage_collector.py
> added solr  to fix bad import from namex

- jobs/auto-analyser-uat/run_auto_analyser_uat.py
issue: https://github.com/bcgov/entity/issues/5443
- see ticket for details
> fixed a couple bugs, added some stuff

- jobs/nr-garbage-collector/Makefile
- jobs/nr-garbage-collector/nr_garbage_collector.py
- jobs/nr-garbage-collector/requirements/prod.txt
Signed-off-by: Chen <Steven.Chen@gov.bc.ca>
*Issue #, have some issues connection to oracle...
* This ticket #5133 is not done yet. The codes will be there so Kial can keep working on this ticket.
> 5133-Update-Garbage-Collector

- jobs/auto-analyser-uat/run_auto_analyser_uat.py
- support/notebooks/names-ops/auto-analyser-uat-stats.ipynb
> notebook update, uat updater bug fix

- api/namex/resources/auto_analyse/issues/abstract/analysis_response_issue.py
- api/namex/resources/auto_analyse/issues/end_designation_more_than_once.py
*bcgov/entity#5464*
- Fixes for highlighting wrong token
Test 1:
Test 2:
Test 3:
Test 4:
Test 5:
> 5464/fixed hightlightings.

- api/namex/resources/mras.py
> Return MRAS GetProfile Response /bcgov/entity#5400

- jobs/nr-garbage-collector/Makefile
- jobs/nr-garbage-collector/config.py
- jobs/nr-garbage-collector/nr_garbage_collector.py
- jobs/nr-garbage-collector/openshift/templates/cronjob.json
- jobs/nr-garbage-collector/openshift/templates/job.json
- jobs/nr-garbage-collector/requirements/prod.txt
https://github.com/bcgov/entity/issues/5133
- see ticket above for details
> 5133 update garbage collector

- jobs/auto-analyser-uat/run_auto_analyser_uat.py
- jobs/auto-analyser-uat/src/auto_analyser_uat/models/uat_job_result.py
- jobs/auto-analyser-uat/src/auto_analyser_uat/version.py
- support/notebooks/names-ops/auto-analyser-uat-stats.ipynb
- updated to prevent uat job result set from hanging in an unfinished state
> updater enhancement to get more results

- jobs/auto-analyser-uat/run_auto_analyser_uat.py
> fixed jobs with no names issue

- api/namex/services/payment/models/__init__.py
/bcgov/entity#5246
SBC Payment response object now includes isPaymentActionRequired.
https://github.com/bcgov/sbc-pay/commit/52326356b955d89741c5f2528ef120df9b938eed
Just update the dataclass on our side.
> Add isPaymentActionRequired

- services/auto-analyze/auto_analyze/analyzer.py
*bcgov/entity#5602*
Catch ValueError exception when attempting to delete a value in dictionary.
> hotfix/5602-MR ZEROS LOGISTICS LTD. crashes search #919

- api/namex/services/payment/models/__init__.py
> Make isPaymentActionRequired optional

- api/namex/constants/__init__.py
- api/namex/services/name_request/name_request_state.py
*Issue #, if available: https://github.com/bcgov/entity/issues/4837
* Added `Incorporate` action to Constants
* Implemented `Incorporate` action when request type is BC and in Approved or Conditionally Approved.
*Notes:*
* This tickets requirements state many different business types and actions where the Title and estimate were focused on this single action. 
* There will need to another ticket to implement the various action types for various business types. Will discuss with team, the goal of MVP, and create a ticket accordingly.
> Added Incorporate Action

- api/namex/resources/payment/payment.py
> Fix payment property typo in payment upgrade code

- api/Jenkinsfiles/build.groovy
> bug fix to jenkinfile

- api/namex/models/request.py
- api/namex/services/name_request/builders/name_analysis_builder.py
*bcgov/entity#5644*
Modified query condensed in one filter to look for descriptive after distinctive to ensure compliance with the order. Before there were two filters in SQL query which did not ensure the order of these categories.
Regression Test:
Test:
VILLAGE DELIGHT DELI LTD.
{'village': 'DIST', 'delight': 'DIST', 'deli': 'DESC'}
The following list shows how distinctive elements are placed before descriptive element which is deli or synonym related (restaurant, food, etc)
name: CHINA VILLAGE CAFE LIMITED, similarity: 0.5
name: CHINESE VILLAGE BUFFET RESTAURANT LTD. similarity: 0.17
name: VILLAGE DELI (MAPLE RIDGE) LTD.similarity: 0.68
name: DAVIE VILLAGE FOOD AND BEVERAGE LTD. similarity: 0.17
name: VILLAGE DELI LTD.  , similarity: 0.68
name: 1998 VILLAGE …
> Ensure searches for conflicts are keeping the order of distinctive before descriptive

- api/namex/models/request.py
- api/namex/resources/payment/payment.py
- api/namex/resources/payment/payment_receipt.py
- api/namex/services/payment/models/__init__.py
- api/namex/services/payment/payments.py
- api/namex/services/payment/receipts.py
> Update Payment Receipts

- services/auto-analyze/src/auto_analyze/analyzer.py
Fix Flake8 and pylint issues related to docstring
> Fix flake8 and pylint issues.

- api/Jenkinsfiles/build.groovy
> rm checkout in pipeline

- api/namex/resources/auto_analyse/paths/xpro_name_analysis/xpro_name_analysis.py
*bcgov/entity#5705:*
Enable Move Request Action for Extra Provincial (XPRO)
Test:
> Enable move request action for XPRO companies.

- api/requirements.txt
> Update req's fix namex-synonyms-api-py-client ref

- api/namex/resources/mras.py
- api/tests/python/__init__.py
- api/tests/python/conftest.py
- api/tests/python/end_points/mras/test_mras.py
- api/tests/python/util.py
Signed-off-by: thor wolpert <thor@wolpert.ca>
*Issue #, if available:* 5400
minimal changes to pass through the MRAS profile in JSON.
other clean up pending:
- MRAS confirmation that JSON formatting is good to go in production
- next PR as this needs to get in for Camerons work
> added pass through for the MRAS profile in JSON

- api/namex/resources/auto_analyse/analysis_options.py
- api/namex/resources/auto_analyse/issues/contains_unclassifiable_word.py
- api/namex/resources/auto_analyse/issues/corporate_name_conflict.py
- api/namex/resources/auto_analyse/issues/designation_mismatch.py
- api/namex/resources/auto_analyse/issues/designation_misplaced.py
- api/namex/resources/auto_analyse/issues/designation_non_existent.py
- api/namex/resources/auto_analyse/issues/name_requires_consent.py
- api/namex/resources/auto_analyse/paths/bc_name_analysis/bc_name_analysis_response.py
- api/namex/resources/auto_analyse/paths/xpro_name_analysis/xpro_name_analysis_response.py
Adding Obtain consent option for xpro corporate conflict issue 
Text updates
> Text updates and updates required for assume name flow

- api/namex/resources/__init__.py
- api/namex/resources/auto_analyse_v2/__init__.py
- api/namex/resources/auto_analyse_v2/api_namespace.py
- api/namex/resources/auto_analyse_v2/name_analysis.py
- api/tests/python/end_points/auto_analyse_v2/configuration.py
- api/tests/python/end_points/auto_analyse_v2/test_name_analysis.py
*Issue #, if available:* /bcgov/entity#5617
Added new endpoint with post, get and delete operations
Added tests
> Namex API - changes for analyzer

- api/namex/resources/auto_analyse/analysis_options.py
Updated the text for alternative assumed name setup
> Text updates for alternative assumed name setup

- api/namex/constants/__init__.py
- api/namex/services/name_request/name_request_state.py
*Issue ##5746*
-  Actions for existing name request
> 5746 Action buttons for existing nr

- api/namex/constants/__init__.py
- api/namex/services/name_request/name_request_state.py
- api/namex/services/payment/client/__init__.py
- api/tests/bash/test-payments.sh
> Implement payment refunds

- api/namex/constants/__init__.py
> RESEND is not required for MVP

- api/namex/resources/auto_analyse/paths/xpro_name_analysis/xpro_name_analysis_response.py
> Adding additional options for XPRO queue conflict issue

- api/namex/services/name_request/auto_analyse/xpro_name_analysis.py
*bcgov/entity#5814:*
- Remove Unclassified words check for XPRO analysis
> 5814- Remove unclassified words check for XPRO analysis

- api/namex/resources/name_requests/name_request.py
- api/namex/resources/payment/payment.py
- api/namex/services/payment/models/__init__.py
- api/namex/services/payment/payments.py
*Issue #5803
- empty object required for sbc pay
> refund error fix

- api/namex/services/name_request/name_request_state.py
> handling negative value

- api/openshift/templates/namex-api-route.dev.json
- api/openshift/templates/namex-api-route.test.json
*Issue #:* https://github.com/bcgov/entity/issues/5861
- these are the changes I made to the route yaml files for namex-api in dev and test (I won't do prod until we verify this has no consequences to other parts of the app)
> changes made in openshift to increase timeout

- api/namex/resources/auto_analyse/paths/xpro_name_analysis/xpro_name_analysis.py
*bcgov/entity#5809:*
- All "Move (continue) into BC a " follow the same flow as new BC company.
> Move(continue)into BC a is handled as new bc company

- api/namex/resources/name_requests/base_nr_resource.py
*Issue:* https://github.com/bcgov/entity/issues/5378
- removed prod feature flag
> removed prod feature flag from disabling namerequest

- Jenkinsfiles/deploy-service.groovy
- api/Jenkinsfiles/deploy-prod.groovy
- api/Jenkinsfiles/deploy-test.groovy
> pipeline fix

- api/namex/resources/auto_analyse/analysis_options.py
*bcgov/entity#5900:*
Change in message in Option 3 for words requiring consent.
For XPRO companies:
> Change message in Option 3

- jobs/inprogress_update/Jenkinsfiles/build.groovy
- jobs/nr-garbage-collector/Jenkinsfiles/build.groovy
> pipeline update for 2 stage build

- api/Makefile
- api/namex/resources/name_requests/abstract_nr_resource.py
- api/namex/resources/name_requests/abstract_nro_resource.py
*Issue #:* https://github.com/bcgov/entity/issues/5645
> edit nr fix

- api/namex/resources/auto_analyse/issues/abstract/analysis_response_issue.py
*bcgov/entity#5812*
Provide correct index when duplicated words:
> Highlight words requiring consent with duplicated words before.

- api/namex/resources/name_requests/name_request.py
- api/namex/resources/name_requests/name_requests.py
> 5928 remap request_entity (entity_type_cd) and request_action (request_action_cd)

- api/namex/resources/name_requests/name_request.py
- api/namex/resources/name_requests/name_requests.py
> Revert "5928 remap request_entity (entity_type_cd) and request_action (request_action_cd)"

- api/namex/resources/auto_analyse/issues/abstract/analysis_response_issue.py
*bcgov/entity#5915:*
Fix for highlighting in name to solve the following:
> 5915/Search Results not highlighting the right word in Red + Results often not showing multiple issues

- api/namex/services/name_request/auto_analyse/protected_name_analysis.py
- api/namex/services/name_request/auto_analyse/xpro_name_analysis.py
- solr-synonyms-api/synonyms/models/synonym.py
> 5950/Commenting check_conflicts_queue for protected and xpro analysis.

- api/namex/models/event.py
- api/namex/models/request.py
- api/namex/services/name_request/auto_analyse/protected_name_analysis.py
- api/namex/services/name_request/auto_analyse/xpro_name_analysis.py
- solr-synonyms-api/synonyms/models/synonym.py
ran:
- git revert 55c14dc44e5dd6a0493baa85114a759d3e539acd
- git revert edc1e40d26fee0cccabbc46436acb0a749637270
> Revert to "fixed edit validation (#981)"

- api/namex/constants/__init__.py
- api/namex/models/state.py
- api/namex/services/name_request/name_request_state.py
> 5988 Pending payment state

- api/namex/models/request.py
- api/namex/resources/requests.py
> 6007 Remove NR L's from NameX Search and Get Next

- api/namex/services/name_request/name_request_state.py
> included retrypayment action callback

- api/namex/models/request.py
- api/namex/services/statistics/wait_time_statistics.py
> 5946 identifying average regular waiting time from the oldest DRAFT nr

- api/namex/resources/payment/payment.py
> Adding Pending Payment to valid state for patch

- api/namex/resources/name_requests/constants.py
> no message

- api/namex/resources/name_requests/abstract_nro_resource.py
> Adding Pending Payment as a valid state for NRO update

- api/namex/__init__.py
- api/namex/resources/statistics/wait_time_statistics.py
- api/namex/services/cache.py
- api/namex/services/statistics/wait_time_statistics.py
- api/requirements.txt
- api/requirements/prod.NoVer.txt
- api/requirements/prod.txt
Added caching.
Removed call to priority in statistics
upgraded JWTManager
Upgraded to new version of werkzeug
> added caching, removed priority call, upgraded JWTManager

- api/namex/resources/payment/payment.py
- api/namex/services/payment/client/__init__.py
- api/namex/services/payment/fees.py
- api/namex/services/payment/invoices.py
- api/namex/services/payment/payments.py
- api/namex/services/payment/receipts.py
Added the code to support cancel payment functionality
> Update PATCH to process CANCEL correctly

- api/namex/resources/name_requests/name_request.py
> Adding Pending Payment to valid state for PUT to support ticket #6170

- api/namex/resources/payment/payment.py
*Issue /bcgov/entity#6137
- review comment from tracey
> 6137 date format as per bc gov guidelines

- api/namex/constants/__init__.py
- api/namex/resources/payment/payment.py
- api/namex/resources/payment/payment_receipt.py
- api/tests/python/end_points/payments/test_payments.py
> Payment test fixes

- api/namex/resources/payment/payment.py
- api/namex/services/name_request/abstract_name_request.py
- api/namex/services/name_request/name_request.py
- jobs/nro-update/nro/nro_datapump.py
*Issue:*https://github.com/bcgov/entity/issues/5840
- fixed expiry/consent date problems (also a PR in name-examination)
> updated expiry date code

- api/namex/resources/payment/payment.py
- api/namex/services/payment/client/__init__.py
- api/namex/services/payment/models/__init__.py
- api/namex/services/payment/payments.py
Issue: https://github.com/bcgov/entity/issues/5331
- made changes to support bcol payment
> updated payment to work for bcol

- api/namex/resources/name_requests/report_resource.py
- api/report-templates/template-parts/name-request/applicantContactInfo.html
- api/report-templates/template-parts/name-request/resultDetails.html
- api/requirements/prod.txt
Added pycountry lookup for displaying country name
*Issue /bcgov/entity#6199:*
Added conditional next action based on request action and entity type
Added pycountry dependency to look up country name using code
> Added conditional next action based on request action and entity type

- api/requirements.txt
> Adding pycountry dependency

- api/namex/resources/name_requests/report_resource.py
- api/report-templates/template-parts/name-request/applicantContactInfo.html
- api/report-templates/template-parts/name-request/resultDetails.html
> Report fixes

- api/namex/models/name.py
> Consumption date fix

- api/namex/resources/name_requests/report_resource.py
> Mapping restoration

- api/namex/resources/name_requests/report_resource.py
> Fix to use Entity type code instead of request type code

- api/namex/models/payment.py
*Issue #, if available:* part of 5975
added find_by_payment_token
> add find by payment token method

- services/namex-pay/src/namex_pay/utils/__init__.py
- services/namex-pay/src/namex_pay/utils/datetime.py
- services/namex-pay/src/namex_pay/worker.py
fix lint errors missed in all the excitement
> fix lint errors missed in all the excitement

- services/namex-pay/Makefile
- services/namex-pay/src/namex_pay/worker.py
- services/namex-pay/tests/unit/test_worker.py
added extra checks for payment state processing
> added extra checks for payment state processing

- services/namex-pay/src/namex_pay/worker.py
changes to log and call the emailer
> changes to log and call the emailer

- api/namex/resources/name_requests/name_request.py
- api/tests/python/end_points/name_requests/test_nr_response.py
*Issue #, bcgov/entity#6335:
Add oldest draft and estimated waiting time data to response for UI (6337)
> 6335 send queue position and time estimate

- jobs/notebook-report/daily/daily.ipynb
Signed-off-by: Chen <Steven.Chen@gov.bc.ca>
Add the total number of NR received for that day to daily notebook report
> Add the total number of NR received for that day #1038

- api/namex/resources/document_analysis.py
changes for namerequest (auth prevents posts for search client and should be a get anyways)
> updated restricted words endpoint to get

- api/namex/resources/document_analysis.py
> added post back in

- api/namex/resources/document_analysis.py
> added get for namerequest prototype

- api/namex/services/statistics/wait_time_statistics.py
> 6812 - adding one to current queue time

- api/namex/resources/payment/__init__.py
- api/namex/resources/payment/payment.py
*Issue #, if available:* bcgov/entity#6507
- see ticket
> cancel payment endpoint

- api/Dockerfile
- api/Makefile
- added Dockerfile
- added targets to Makefile
> adding Dockerfile

- api/namex/constants/__init__.py
*Issue #, if available:* https://github.com/bcgov/entity/issues/6553
> add renew button back

- api/namex/services/nro/oracle_services.py
- added the oracle error message to the log
> added the oracle errormessage to the log

- api/Dockerfile
- changed to explicitly use the 64bit library and version
> changed to explicitly use the 64bit library and version

- api/namex/constants/__init__.py
- api/namex/models/payment.py
- api/namex/resources/name_requests/name_request.py
- api/namex/resources/payment/payment.py
- api/namex/services/name_request/utils.py
- api/requirements.txt
- services/namex-pay/src/namex_pay/worker.py
- services/namex-pay/tests/unit/test_worker.py
*Issue #, if available:* https://github.com/bcgov/entity/issues/7332
- fixed pay logic around PAD and payment action mismatch
> fixed pay issues

- services/namex-pay/src/namex_pay/worker.py
> fixed queue error

- api/namex/resources/payment/payment.py
- services/namex-pay/src/namex_pay/worker.py
*Issue #, if available:*  https://github.com/bcgov/entity/issues/7332
> updated payment flow to fix instant completion

- api/namex/resources/payment/payment.py
> fixed PAD pay issues

- api/namex/resources/payment/payment.py
> fixed receipt issue

- .github/workflows/auto-analyze-ci.yml
- .github/workflows/colin-api-ci.yml
- .github/workflows/inprogress-update-cd.yml
- .github/workflows/inprogress-update-ci.yml
- .github/workflows/namex-api-ci.yml
- .github/workflows/namex-pay-cd.yml
- .github/workflows/namex-pay-ci.yml
- .github/workflows/notebook-report-cd.yml
- .github/workflows/nro-extractor-cd.yml
- .github/workflows/nro-extractor-ci.yml
- .github/workflows/nro-update-cd.yml
- .github/workflows/nro-update-ci.yml
- .github/workflows/solr-admin-app-ci.yml
- .github/workflows/solr-feeder-cd.yml
- .github/workflows/solr-feeder-ci.yml
- .github/workflows/solr-synonyms-api-cd.yml
- .github/workflows/solr-synonyms-api-ci.yml
- api/namex/resources/name_requests/name_request.py
- api/namex/services/statistics/wait_time_statistics.py
- api/namex/utils/api_resource.py
- codecov.yaml
- jobs/inprogress_update/Dockerfile
- jobs/inprogress_update/openshift/templates/bc.yaml
1. Fixed timedelta issue;
2. Update inprogress update job' docker file to use 64bit Oracle libraries;
3. Fixed typos;
> Fixed timedelta issue and inprogress update docker file issue.

- api/namex/resources/payment/payment.py
> fixed new NR return error

- api/namex/resources/name_requests/name_request.py
- api/namex/resources/name_requests/name_requests.py
> fixed wait time error

- api/namex/resources/payment/payment.py
> fixed completion date being added too early

- api/namex/resources/payment/payment_receipt.py
*Issue #:  /bcgov/entity#6017*
- Fixed Submission Date & Time formatting
> 6017 - NR receipt should show date and time in local time

- api/migrations/versions/b0fc67a096fe_.py
> imported error type

- api/migrations/versions/b0fc67a096fe_.py
- one liner to fix migration check (will not affect dev/test/prod since they already have the cd, but is needed for the tests and local development)
> 6609 fix migration

- api/namex/models/user.py
- api/namex/resources/payment/payment.py
- api/namex/utils/auth.py
> 6555 Add Staff ability to file and pay

- api/namex/resources/events.py
- api/namex/resources/payment/payment.py
> small fixes

- api/namex/services/payment/models/__init__.py
> 6555 missing keys

- api/namex/resources/events.py
- api/namex/resources/name_requests/name_request.py
- api/namex/resources/payment/payment.py
- api/namex/services/nro/oracle_services.py
- jobs/inprogress_update/inprogress_update.py
- jobs/nro-extractor/extractor/app.py
- jobs/nro-update/nro/nro_datapump.py
- services/namex-pay/src/namex_pay/worker.py
*Issue #, if available:* 
- https://github.com/bcgov/entity/issues/7187
- https://github.com/bcgov/entity/issues/7521
- https://github.com/bcgov/entity/issues/7704
- https://github.com/bcgov/entity/issues/6423
- multiple small fixes/adds for txn history + syncing with NRO
> multiple small fixes/adds for txn history + syncing with NRO

- api/namex/services/payment/models/__init__.py
> 6556 Receipts display correctly

- jobs/nro-extractor/extractor/app.py
- services/namex-pay/src/namex_pay/worker.py
> fix for pay update issue/duplicate nr issue

- jobs/nro-extractor/extractor/app.py
> updated extractor to update feeder row for new ones we skip

- jobs/nro-extractor/Dockerfile
> Update the Oracle client version in Dockerfile.

- jobs/nro-extractor/requirements/dev.txt
- jobs/nro-update/Dockerfile
- services/namex-pay/Dockerfile
- services/namex-pay/devops/vaults.json
> namex-pay/nro-update oracle connection stuff

- api/namex/resources/events.py
> txn history fix for old bad data

- api/namex/resources/payment/payment.py
> 7818 consider waive fees before clearing headers

- api/namex/resources/payment/payment.py
*Issue #: /bcgov/entity#7399
* Updated/moved logic for retrieving/populating folio such that even consumers of endpoint without auth and staff role are able to pass folio to payment service through headers
> 7399 send folio to auth api

- api/namex/services/nro/consume_nr.py
*Issue #, if available:*precursor to 6033
- adding consume_nr to the NRO services
> added consume nr to the NRO services.

- api/namex/resources/payment/payment.py
- services/namex-pay/src/namex_pay/config.py
- services/namex-pay/src/namex_pay/worker.py
*Issue #, if available:* https://github.com/bcgov/entity/issues/7704
> conditional bug fix for syncing with nro

- api/namex/resources/requests.py
- api/namex/services/name_request/name_request_state.py
- api/namex/services/nro/change_nr.py
*Issue #, if available:* https://github.com/bcgov/entity/issues/7704
> fixed renewal saving wrong date to nro

- api/namex/models/name.py
- api/namex/resources/requests.py
- api/tests/python/models/test_request.py
- jobs/name-search-script/add_name_search.py
- jobs/name-search-script/config.py
- jobs/name-search-script/requirements.txt
- jobs/name-search-script/requirements/bcregistry-libraries.txt
> namex search update fixes

- api/namex/models/name.py
> apostrophe issue

- api/namex/resources/requests.py
> needed search change

- api/namex/resources/requests.py
- api/namex/services/nro/oracle_services.py
> 6033 consume nr

- jobs/nro-extractor/extractor/app.py
- update to allow updates from NRO if the NR is in draft and there is not a payment in progress in namex
> extractor update to allow edits from NRO

- api/namex/services/nro/add_nr.py
*Issue #6566:*
- Added upper() to insert statement
*The issue with home_juris_num will be fixed in namerequest*
> 6566 - Capitalized xpro_jurisdiction in request_instance table

- jobs/nro-extractor/extractor/app.py
> prevent nro-extractor updating completed NRs that are unfurnished

- jobs/notebook-report/openshift/templates/cronjob.yaml
- jobs/notebook-report/weekly/weeklyrestoration.ipynb
*Issue #, if available:* #8013
Restoration Expiry Weekly Notebook Report
> Restoration Expiry Weekly Notebook Report

- api/namex/resources/events.py
*Issue #, if available:* https://github.com/bcgov/entity/issues/8025
- small trxn history fix
> handle empty event data

- api/namex/resources/name_requests/name_request.py
- api/namex/services/name_request/name_request_state.py
- api/namex/services/name_request/utils.py
> 7804 download receipt once cancelled and refunded

- api/namex/services/name_request/name_request_state.py
> 7384 remove renew if consumed

- api/namex/constants/__init__.py
> 8167 fix pending payment action response

- api/.dockerignore
- api/namex/__init__.py
- api/namex/models/request.py
- api/namex/services/lookup/__init__.py
- api/namex/services/lookup/nr_filing_actions.py
- api/requirements/dev.txt
- api/setup.cfg
- api/tests/python/services/lookup/test_nr_filing_actions.py
*Issue #, if available:* ops-day-nrtypes
added an nr_type to actions lookup,
incl in the request.json()
> added an nr_type to actions mapping, incl in the request.json()

- api/namex/models/request.py
- api/namex/services/lookup/__init__.py
- api/namex/services/lookup/name_request_filing_actions.py
- api/tests/python/models/test_request.py
- api/tests/python/services/lookup/test_nr_filing_actions.py
- member call was deleted before prior merge, added it back
> fix type, member call deleted to prior merge

- api/namex/resources/auto_analyse/paths/name_analysis/name_analysis.py
- api/namex/services/name_request/builders/name_analysis_builder.py
*Issue #, if available:* https://github.com/bcgov/entity/issues/8261
- fixed distinctive check (was timing out in some cases), removed unneeded validation that was incorrect, added strip for special chars in the name
> name analysis endpoint fixes

- jobs/nr-day-job/Dockerfile
- jobs/nr-day-job/devops/vaults.json
> 7388 nats emailer vault

- jobs/nr-day-job/run.sh
> 7388 typo fix

- api/namex/constants/__init__.py
- api/namex/resources/auto_analyse/issues/add_descriptive_word.py
- api/namex/resources/auto_analyse/issues/contains_unclassifiable_word.py
- api/namex/resources/auto_analyse/issues/contains_words_to_avoid.py
- api/namex/resources/auto_analyse/issues/designation_mismatch.py
- api/namex/resources/auto_analyse/issues/designation_misplaced.py
- api/namex/resources/auto_analyse/issues/end_designation_more_than_once.py
- api/namex/resources/auto_analyse/issues/incorrect_year.py
- api/namex/resources/auto_analyse/issues/word_special_use.py
- api/namex/resources/auto_analyse/paths/name_analysis/name_analysis.py
- api/namex/services/name_request/auto_analyse/__init__.py
- api/namex/services/name_request/auto_analyse/mixins/set_designation_lists.py
- api/namex/services/name_request/auto_analyse/unprotected_name_analysis.py
*Issue #, if available:* https://github.com/bcgov/entity/issues/7960
- multiple bugs fixed with this PR
> name analysis updates

- api/namex/resources/events.py
*Issue #, if available:* https://github.com/bcgov/entity/issues/8409
> names viewer access allowed for transaction history

- jobs/nr-day-job/devops/vaults.json
> 7388 change vault to namex-api

- jobs/nr-day-job/k8s/Readme.md
- jobs/nr-day-job/k8s/templates/cronjob.yaml
> 7388 command change

- jobs/nr-day-job/nr_day_job.py
> 7388 fix app context error

- api/namex/resources/payment/payment_fees.py
- api/namex/services/payment/client/__init__.py
- api/namex/services/payment/fees.py
> 8480 add staff auth header to fee calculation

- api/namex/services/payment/models/__init__.py
Issue #: /bcgov/entity#8497
* add paymentAccount property to conform with latest pay api changes
> 8497 add paymentAccount property to conform with latest pay api changes

- api/namex/resources/events.py
> 8554 fix transaction history for resubmit

- .github/workflows/solr-names-updater-cd.yml
- .github/workflows/solr-names-updater-ci.yml
*Issue #: bcgov/entity#7980
* add GH CI/CD workflows
> 7980 Add github CI/CD workflows for solr-names-updater

- .github/workflows/solr-names-updater-ci.yml
- services/solr-names-updater/Makefile
- services/solr-names-updater/src/solr_names_updater/worker.py
- services/solr-names-updater/tests/unit/test_version.py
*Issue #: bcgov/entity#7980
* fixes to get CI running successfully
> 7980 fix issues to get CI running for solr-names-updater

- api/namex/models/name.py
> track corpNum instead of consumptionDate

- api/namex/models/name.py
- jobs/nro-extractor/extractor/app.py
> 8721 nro extractor fix

- api/namex/models/name.py
To fix nro-extractor from failing
> removed nr.json call

- api/namex/models/name.py
- jobs/nro-extractor/extractor/app.py
> logs added

- api/namex/models/name.py
- api/namex/utils/queue_util.py
> moved state change to below to check the connection issue

- api/namex/models/name.py
- jobs/nro-extractor/extractor/app.py
> adding an additional event listener to set consumed state

- api/namex/resources/payment/payment.py
> 8908 fixed comparing time issue

- api/namex/constants/__init__.py
- jobs/nro-update/nro/nro_datapump.py
- jobs/nro-update/nro_update.py
> 7087 test restore bug

- jobs/nro-update/nro_update.py
> cast expires_days to int

- api/namex/services/lookup/name_request_filing_actions.py
> legalType for changeofname sp and gp

- api/namex/services/nro/request_utils.py
- jobs/nro-extractor/requirements/bcregistry-libraries.txt
*Issue #10280
nro-extractor pulls in expiration-date of time 00:00:00   fix to set to 6:59 UTC/TZ
> 10280 expiration date bugfix

- .github/workflows/solr.cd.yml
- solr/Makefile
- solr/cores/search/conf/managed-schema
*Issue #, if available:* bcgov/entity#12185
> new fields and gha tag pipeline

- .github/workflows/solr.cd.yml
> fixed solr cd

- solr/Makefile
> fixed makefile

- solr/Makefile
> fix cd pipeline

- solr/cores/search/conf/managed-schema
- solr/cores/search/conf/solr-data-config.xml
*Issue #, if available:* bcgov/entity#12185
> search core: changed field names to match api spec

- solr/cores/search/conf/solr-data-config.xml
*Issue #, if available:* https://github.com/bcgov/entity/issues/12402
> updated search data import config for colin data

- .github/workflows/inprogress-update-ci.yml
- api/namex/models/payment.py
- api/namex/resources/payment/payment.py
*Issue #, if available:* https://github.com/bcgov/entity/issues/12596
Check any existing payment exists. If yes, then reuse the invoice (payment).
> 12596 reuse invoice

- .github/workflows/namex-api-ci.yml
- api/Dockerfile
- api/Makefile
- api/namex/resources/requests.py
- api/namex/services/nro/oracle_services.py
- api/namex/services/queue.py
- colin-api/Dockerfile
- colin-api/requirements.txt
- colin-api/requirements/prod.txt
- colin-api/src/colin_api/logging.conf
*Issue #:*  https://github.com/bcgov/entity/issues/12807
1. Fixed colin api logging file location issue.
2. The existing NATS STAN client couldn't upgrade to python 3.10; we have to wait the new version or find another way to use NATS.
> Fixed colin api logging issue and rollback namex api python to 3.8 .

- api/namex/resources/requests.py
- api/tests/python/end_points/test_namex_search.py
*Issue #, if available:* https://github.com/bcgov/entity/issues/11538
Query for multiple nr_numbers
> 11538 - Query for multiple nr_numbers

- colin-api/src/colin_api/resources/v1/corporations.py
https://github.com/bcgov/entity/issues/13013
Replaced the double quotes with single quotes in the SQL strings.
> 13013 Name request validation incorporation number failed

- solr-feeder/solr_feeder/endpoints/feeds.py
- solr-feeder/solr_feeder/endpoints/probes.py
*Issue #, if available:* https://github.com/bcgov/entity/issues/13574
> fix url prefixes

- solr-feeder/devops/vaults.json
*Issue #, if available:* https://github.com/bcgov/entity/issues/13574
> add needed vaults

- solr-feeder/solr_feeder/services/colin.py
*Issue #, if available:* https://github.com/bcgov/entity/issues/13574
> add BC prefix to bc limited records

- solr-feeder/solr_feeder/services/colin.py
*Issue #, if available:* https://github.com/bcgov/entity/issues/13574
> update state correctly

- jobs/nr-duplicates-report/openshift/templates/cronjob.yaml
- jobs/nr-duplicates-report/run.sh
Signed-off-by: Steven Chen <steven.chen@gov.bc.ca>
*Issue #, if available:* 14287
Tried to fix the error: /bin/sh: 1: ./run.sh: not found for previous deployed
> NR Duplicates Report#14287

- api/report-templates/template-parts/name-request/resultDetails.html
*Issue #14522
roll back consent letter change for future
> 14522_rollback

- solr-feeder/devops/vaults.json
> solr-feeder-update-vault

- api/namex/models/request.py
- api/namex/resources/requests.py
- api/tests/python/end_points/test_namex_search.py
*Issue #, if available:* bcgov/entity/issues/15175
> 15175 - Changes for search for SBC-AUTH.

- api/namex/models/request.py
- api/namex/resources/requests.py
- api/tests/python/end_points/test_namex_search.py
Reverts bcgov/namex#1342
Needs unit tests to pass.. I'm working on fixing the unit tests so all the code changes work hopefully.
> Revert "15175 - Changes for search for SBC-AUTH."

- api/tests/python/end_points/test_requests.py
- api/tests/python/end_points/util.py
- api/tests/python/models/test_request.py
[*Issue #, if available:*](https://github.com/bcgov/entity/issues/15175)
> fixed some unit testing

- api/namex/models/request.py
- api/namex/resources/requests.py
> 15175 - Add in expiration date.

- jobs/nro-extractor/extractor/app.py
https://github.com/bcgov/entity/issues/15700
add condition for no payment NR in nro-extractor
> 15700 no fee NR can not be "consumed"

- namex-db/openshift/templates/backup.yaml
> add pager duty alert key

- api/namex/models/request.py
- api/namex/resources/requests.py
> Add in consent flag for auth-web dashboard.

- api/requirements.txt
- colin-api/requirements.txt
- jobs/nr-day-job/requirements.txt
> set latest sentry sdk version

- colin-api/requirements.txt
> bump urllib3 to satisfy launchdarkly and sentry requirements

- api/devops/vaults.json
- api/namex/resources/name_requests/name_request.py
> Fixed missing environment variables issue.

- jobs/nro-extractor/Dockerfile
- jobs/nro-update/Dockerfile
*Issue # [16070](https://github.com/bcgov/entity/issues/16070)
> increase log level entity#16070

- api/namex/resources/flask_threads.py
- api/namex/resources/requests.py
*Issue #, if available: https://github.com/bcgov/entity/issues/16349
*Description of changes: fire and forget emails to unblock api route
> fire-and-forget emails

- solr-feeder/solr_feeder/services/colin.py
- solr-feeder/solr_feeder/version.py
*Issue #, if available:* https://github.com/bcgov/entity/issues/16894
> added email to business obj for update

- solr/cores/possible.conflicts/conf/managed-schema
*Issue #, if available:* https://github.com/bcgov/entity/issues/16732
*Description of changes:* limit number of synonyms used to avoid too-many-boolean-clauses exception
> 16732 - solr boolean clause error

- solr-feeder/solr_feeder/config.py
- solr-feeder/solr_feeder/services/search.py
- solr-feeder/solr_feeder/version.py
*Issue #, if available:* https://github.com/bcgov/entity/issues/17227
> feeder update for bor solr timeouts during import flow

- solr-feeder/app.py
- solr-feeder/solr_feeder/services/search.py
- solr-feeder/solr_feeder/version.py
*Issue #, if available:* https://github.com/bcgov/entity/issues/17227
> feeder: improve logging

- api/namex/resources/payment/payment.py
*Issue #, if available: [entity/issues/17411](https://github.com/bcgov/entity/issues/17411)
Looks like this was caused by https://github.com/bcgov/namex/pull/1254 that was addressing https://github.com/bcgov/entity/issues/12596
I added to check that a REAPPLY transaction that falls within the correct timeframe is allowed to proceed
> 17411 - don't skip valid cases of reapply payments

- solr-feeder/solr_feeder/services/colin.py
- solr-feeder/solr_feeder/version.py
*Issue #, if available:* https://github.com/bcgov/entity/issues/15978
> solr-feeder:pass good standing along

- solr-feeder/solr_feeder/services/colin.py
- solr-feeder/solr_feeder/services/search.py
*Issue # https://github.com/bcgov/entity/issues/17752
> Add token into colin-api call

- solr-feeder/solr_feeder/services/colin.py
- solr-feeder/solr_feeder/services/search.py
- solr-feeder/solr_feeder/version.py
*Issue #, if available:* https://github.com/bcgov/entity/issues/17752
> FEEDER: add token inside party colin calls too

- nro-legacy/sql/object/registry/colin_mgr/trigger/namex_corporation_qmsg.sql
*Issue #, if available:* https://github.com/bcgov/entity/issues/15978
> Oracle trigger: documenting changes being applied by david r

- solr-feeder/solr_feeder/services/colin.py
- solr-feeder/solr_feeder/version.py
*Issue #, if available:* https://github.com/bcgov/entity/issues/17640
> Solr-feeder: nds update to ignore garbage data

- api/namex/resources/name_requests/report_resource.py
- api/report-templates/emails/rejected.md
- api/report-templates/nameRequest.html
*Issue #, if available:* https://github.com/bcgov/entity/issues/15665
> Email tweaks

- nro-legacy/sql/object/registry/colin_mgr/trigger/namex_corporation_qmsg.sql
*Issue #, if available:* https://github.com/bcgov/entity/issues/15978
> documenting oracle trigger update

- jobs/nro-extractor/Makefile
- jobs/nro-update/config.py
- jobs/nro-update/nro/nro_datapump.py
- jobs/nro-update/nro_update.py
- jobs/nro-update/openshift/templates/deployment.yaml
- jobs/nro-update/tests/test_nro_datapump.py
https://github.com/bcgov/entity/issues/15818
1. removed environment variable EXPIRES_DAYS
2. fixed the error 'InstrumentedList' object has no attribute 'all'
> 15818 NAMES/Society Restoration Incorrect Expire Date

- api/namex/resources/requests.py
> 18035 name request search with single quote

- api/namex/resources/name_requests/report_resource.py
*Issue #:* https://github.com/bcgov/entity/issues/17859
*Description of changes:* fix expiration date formatting for nr result
> 17859 - remove unnecessary date formatting

- api/report-templates/emails/approved-modernized.md
- api/report-templates/emails/conditional-modernized.md
*Issue #, if available:* https://github.com/bcgov/entity/issues/15665
> 15665 - switch url var for modernized nr result letter

- api/report-templates/emails/approved-colin.md
- api/report-templates/emails/approved-modernized.md
- api/report-templates/emails/approved-so.md
- api/report-templates/emails/approved.md
- api/report-templates/emails/conditional-colin.md
- api/report-templates/emails/conditional-modernized.md
- api/report-templates/emails/conditional-so.md
- api/report-templates/emails/conditional.md
https://github.com/bcgov/entity/issues/18240
update the wording of approved/conditional approved letters
> 18240 - update the wording of approved/conditional approved letters

- nro-legacy/sql/object/names/namex/package/solr_pkb.sql
*Issue #, if available:* https://github.com/bcgov/entity/issues/18841
This is only a change to namex documentation. The actual sql is being updated by David R. in NAMESP
> Updating namex namesp sql documentation (not part of any deployments)

- api/namex/resources/name_requests/report_resource.py
bcgov/entity#20142
This PR fixes Society NRs being emailed the wrong consent letter.
> 20142 Update entity and action code when emailing consent

- solr-feeder/solr_feeder/services/colin.py
- solr-feeder/solr_feeder/version.py
*Issue #, if available:* https://github.com/bcgov/entity/issues/20023
> SOLR-FEEDER - add business address in bor solr update

- api/namex/resources/requests.py
*Issue 20887
Since I am feeling that my changes wasn't deployed on dev, I am making this PR to deploy again.
> Replacing Date Formation

- api/poetry.lock
- api/pyproject.toml
> update namex api source

- jobs/nr-day-job/poetry.lock
- jobs/nr-day-job/pyproject.toml
- jobs/nro-extractor/poetry.lock
- jobs/nro-extractor/pyproject.toml
- services/emailer/poetry.lock
- services/emailer/pyproject.toml
- services/namex-pay/poetry.lock
- services/namex-pay/pyproject.toml
- services/solr-names-updater/poetry.lock
- services/solr-names-updater/pyproject.toml
> More source updates

- services/emailer/poetry.lock
- services/emailer/pyproject.toml
> Update emailer source

- api/Makefile
- jobs/nr-day-job/Makefile
- jobs/nro-extractor/Makefile
- services/namex-pay/Makefile
- services/solr-names-updater/Makefile
> poetry saves libs to .venv, not venv; use python3.12 explicitly

- api/namex/resources/events.py
> 22774 update events to show the corpNum in consumed transaction

- api/migrations/versions/179a7b0089ce_payment_societies.py
> Create 2 new API requests for the Home Team #22774

- services/namex-pay/src/namex_pay/resources/worker.py
- services/namex-pay/src/namex_pay/version.py
https://github.com/bcgov/entity/issues/23464
bug fix: namex-pay does not log payment complete event
> 23464 bug fix: namex-pay does not log payment complete event

- .github/workflows/namex-pay-cd.yml
> CD: update to build using feature branch

- .github/workflows/namex-pay-cd.yml
> fix: update working directory

- jobs/notebook-report/devops/gcp/clouddeploy.yaml
- services/solr-names-updater/devops/gcp/clouddeploy.yaml
- solr-feeder/devops/gcp/clouddeploy.yaml
> refactor: prepend namex before service/container names

- services/emailer/src/namex_emailer/email_templates/NR-BEFORE-EXPIRY-MODERNIZED-CONT-IN.html
*Issue #, if available:* https://app.zenhub.com/workspaces/names-team-board-new-655554cbddd49510027dad2e/issues/gh/bcgov/entity/24167
- Add template for NR about to expire for continue in rrequests
> 24167 -  add email template for before expiry for continue in requests

- services/emailer/src/namex_emailer/email_templates/NR-EXPIRED-CONT-IN.html
*Issue #, if available:* https://app.zenhub.com/workspaces/names-team-board-new-655554cbddd49510027dad2e/issues/gh/bcgov/entity/24169
- Add email template for NR expired for continue in requests
> 24169 add email template for expired continue in requests

- solr/cores/search/conf/solrconfig.xml
> fix: bump up number of max boolean clauses

- jobs/sftp-nuans-report/Dockerfile
https://github.com/bcgov/entity/issues/24077
update pip version to most recent to avoid dead loops
> Update Dockerfile pip version

- jobs/notebook-report/devops/gcp/clouddeploy.yaml
- jobs/nr-day-job/devops/gcp/clouddeploy.yaml
- jobs/nr-duplicates-report/devops/gcp/clouddeploy.yaml
> fix: change service to job name

- solr/README.md
*Issue #, if available:* https://github.com/bcgov/entity/issues/24511
Documented key components of the Namex SOLR implementation.
> SOLR Documentation

- .github/workflows/bad-name-notifier-CI.yml
https://github.com/bcgov/entity/issues/24774
Create workflow bad-name-notifier-CI.yml
> Create workflow bad-name-notifier-CI.yml

- .github/workflows/emailer-cd-gcp.yml
> cd: update cd name

- .github/workflows/emailer-cd-gcp.yml
- services/emailer/devops/gcp/clouddeploy.yaml
> Change cd name

- services/emailer/devops/gcp/clouddeploy.yaml
> fix service account names

- services/emailer/src/namex_emailer/email_processors/nr_result.py
- services/emailer/src/namex_emailer/resources/worker.py
- services/emailer/src/namex_emailer/services/helpers.py
*Issue #, if available: #24225*
Add the loggers for debug
> 24225 debug emaler

- services/emailer/src/namex_emailer/email_processors/nr_result.py
> 24225_update_debug_code

- jobs/sftp-nuans-report/notebook/generate_files.ipynb
https://github.com/bcgov/entity/issues/24077
Add a linefeed at the end of the report
> 24077 NRO Decommission: Create file to send to NUANS from NAMEX (replaces current process in NAMESP)

- .github/workflows/sftp-nuans-report-cd.yml
[24077](https://github.com/bcgov/entity/issues/24077)
create CI and CD workflow for the report job
> Create sftp-nuans-report work flows

- services/emailer/poetry.lock
In my previous PR for the API: 
> emailer uses latest version of namex api

- api/namex/resources/name_requests/report_resource.py
- api/namex/services/flags.py
- api/tests/python/services/test_flags.py
- services/emailer/poetry.lock
- services/emailer/src/namex_emailer/email_processors/nr_notification.py
- services/emailer/src/namex_emailer/email_processors/nr_result.py
- services/emailer/src/namex_emailer/services/helpers.py
*Issue #, if available: #25167*
> 25167 feature flgas enable won emails

- services/emailer/src/namex_emailer/email_templates/conditional-new.md
*Issue #, if available: #25256*
Update language in Conditionally Approved Name Request Email
- Add additional steps to the section: "Option 2: Use BC Corporate Online"
- Send in your consent letter to [BCregistries@gov.bc.ca](mailto:BCregistries@gov.bc.ca)
- Receive confirmation that the consent letter has been accepted
- Update the numbering for the rest of the steps
> 25256_update_email_content

- api/namex/resources/name_requests/report_resource.py
- services/emailer/poetry.lock
*Issue #, if available: bcgov/entity#25356*
> 25356 update_outputs_CHG_CNV_NR

- jobs/inprogress_update/requirements.txt
It can be built in my local but I don't know why it failed in my previous PR so try this one.
> 25908 - NRs stuck in state: IN PROGRESS - please investigate and fix

- api/namex/resources/name_requests/report_resource.py
- services/emailer/poetry.lock
- services/emailer/src/namex_emailer/email_templates/NR-BEFORE-EXPIRY-REH.html
- services/emailer/src/namex_emailer/email_templates/approved-reh.md
- services/emailer/src/namex_emailer/email_templates/conditional-reh.md
- services/emailer/src/namex_emailer/email_templates/consent-reh.md
*Issue #, if available: #25622*
> 25622 fix_get_env_name

- jobs/inprogress_update/config.py
- jobs/inprogress_update/inprogress_update.py
> init pubsub queue

- services/emailer/src/namex_emailer/email_templates/conditional-reh.md
*Issue #, if available: #25622*
> 25622_fix_typo

- jobs/bad-designation-notifier/src/services/database_service.py
https://github.com/bcgov/entity/issues/25898
> 25898 Update database_service.py

- api/namex/resources/requests.py
Hot fix for object of type 'NoneType'#26195
> 26195 - Hot fix for object of type NoneType

- .github/workflows/solr-synonyms-api-cd.yml
- .github/workflows/solr-synonyms-api-ci.yml
> truncate app name

- api/namex/resources/name_requests/name_request.py
https://github.com/bcgov/entity/issues/25261
Explicitly call db.session.commit() when saving edits to ensure changes are not missed.
> #25261 Explicitly call db.session.commit() when saving edits

- jobs/notebook-report/src/daily/daily.ipynb
Updated the date format for the csv file
> 23714 - GCP: Build Notebook Report Job

- solr-feeder/poetry.lock
- solr-feeder/pyproject.toml
- solr-feeder/solr_feeder/__init__.py
- solr-feeder/solr_feeder/endpoints/feeds.py
- solr-feeder/solr_feeder/services/auth.py
- solr-feeder/solr_feeder/services/colin.py
- solr-feeder/solr_feeder/services/search.py
- solr-feeder/solr_feeder/solr.py
> 23712 solr feeder use gcp structured logging

- solr-feeder/solr_feeder/services/search.py
> fix incorrect logging level for a log statement

- .github/workflows/namex-api-cd.yml
> Update namex-api-cd.yml to ubuntu

- .github/workflows/namex-api-cd.yml
> Update namex-api-cd.yml ubuntu version

- .github/workflows/namex-api-cd.yml
- api/Makefile
- Reverted OCP changes that went in this morning. 
> revert changes to main

- .github/workflows/namex-api-cd.yml
- api/devops/gcp/clouddeploy.yaml
> cicd tweaks

- services/emailer/src/namex_emailer/email_templates/AML/NR-RENEWAL.html
- services/emailer/src/namex_emailer/email_templates/ASSUMED/NR-RENEWAL.html
- services/emailer/src/namex_emailer/email_templates/CHG-ASSUM/NR-RENEWAL.html
- services/emailer/src/namex_emailer/email_templates/CHG/NR-RENEWAL.html
- services/emailer/src/namex_emailer/email_templates/CNV/NR-RENEWAL.html
- services/emailer/src/namex_emailer/email_templates/DBA/NR-RENEWAL.html
- services/emailer/src/namex_emailer/email_templates/MVE/NR-RENEWAL.html
- services/emailer/src/namex_emailer/email_templates/NEW/NR-RENEWAL.html
- services/emailer/src/namex_emailer/email_templates/NRO-NEWAML/NR-RENEWAL.html
- services/emailer/src/namex_emailer/email_templates/NRO-REST/NR-RENEWAL.html
- services/emailer/src/namex_emailer/email_templates/REH/NR-RENEWAL.html
- services/emailer/src/namex_emailer/email_templates/REN/NR-RENEWAL.html
- services/emailer/src/namex_emailer/email_templates/RESUBMIT/NR-RENEWAL.html
- services/emailer/src/namex_emailer/email_templates/common/NR-RENEWAL.html
Issue #: /https://github.com/bcgov/entity/issues/27130
- Update NR Renewal templates
NRO-REST and REH template:
All other NR template:
> 27130-Update-NR-Renewal-Emails

- services/emailer/src/namex_emailer/email_templates/AML/NR-RENEWAL.html
- services/emailer/src/namex_emailer/email_templates/ASSUMED/NR-RENEWAL.html
- services/emailer/src/namex_emailer/email_templates/CHG-ASSUM/NR-RENEWAL.html
- services/emailer/src/namex_emailer/email_templates/CHG/NR-RENEWAL.html
- services/emailer/src/namex_emailer/email_templates/CNV/NR-RENEWAL.html
- services/emailer/src/namex_emailer/email_templates/DBA/NR-RENEWAL.html
- services/emailer/src/namex_emailer/email_templates/MVE/NR-RENEWAL.html
- services/emailer/src/namex_emailer/email_templates/NEW/NR-RENEWAL.html
- services/emailer/src/namex_emailer/email_templates/NRO-NEWAML/NR-RENEWAL.html
- services/emailer/src/namex_emailer/email_templates/NRO-REST/NR-RENEWAL.html
- services/emailer/src/namex_emailer/email_templates/REH/NR-RENEWAL.html
- services/emailer/src/namex_emailer/email_templates/REN/NR-RENEWAL.html
- services/emailer/src/namex_emailer/email_templates/RESUBMIT/NR-RENEWAL.html
- services/emailer/src/namex_emailer/email_templates/common/NR-RENEWAL.html
Issue #: /https://github.com/bcgov/entity/issues/27130
- Designs were swapped
> 27130 - Update RENEWAL NR Emails

- jobs/sftp-nuans-report/sftp_nuans_report/notebook/generate_files.ipynb
> fix db connection to work in gcp for sftp nuans job

- api/namex/resources/events.py
https://github.com/bcgov/entity/issues/20384
fix a bug
> 20384 update the new event post

- services/emailer/src/namex_emailer/resources/worker.py
https://github.com/bcgov/entity/issues/28408
fix a bug
> 28408 fix bug to accept resendEventId

- services/emailer/src/namex_emailer/services/helpers.py
https://github.com/bcgov/entity/issues/28408
fix a bug
> 28408 fix a bug

- services/emailer/src/namex_emailer/email_processors/resend.py
- services/emailer/src/namex_emailer/resources/scheduled_email_handler.py
- services/emailer/src/namex_emailer/resources/worker.py
- services/emailer/src/namex_emailer/services/helpers.py
https://github.com/bcgov/entity/issues/28408
fix a bug
> 28408 async record events

- services/emailer/config.py
- services/emailer/tests/conftest.py
- services/emailer/tests/pytest_marks.py
- services/emailer/tests/unit/email_processors/test_get_template.py
- services/emailer/tests/unit/email_processors/test_nr_notification.py
- services/emailer/tests/unit/test_configuration.py
- services/emailer/tests/unit/test_worker.py
*Issue #, if available:* https://github.com/bcgov/entity/issues/29003
Fix CI Unit tests
> 29003 namex emailer unit testing

- .github/workflows/solr-synonyms-api-cd.yml
- api/devops/gcp/clouddeploy.yaml
- solr-synonyms-api/devops/gcp/clouddeploy.yaml
> 22554-Deploy Names Applications to SANDBOX

- api/namex/resources/requests.py
- api/namex/services/lookup/name_request_filing_actions.py
*Issue #, if available:* bcgov/entity#30327
*Description of changes:* 
Added SP GP Filter Case
> 30327 nr type spgp
